// frontend/angular/src/app/pages/login/login.component.ts
import { Component, ChangeDetectionStrategy, inject } from '@angular/core';
import { HttpErrorResponse } from '@angular/common/http';
import { FormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { AuthService } from '../../core/auth.service';
import { TranslateService } from '../../core/i18n/translate.service';
import { TranslatePipe } from '../../core/i18n/translate.pipe';

@Component({
  selector: 'app-login',
  changeDetection: ChangeDetectionStrategy.Eager,
  imports: [FormsModule, RouterLink, TranslatePipe],
  template: `
    <main class="page">
      <div class="card">
        <h1 class="title">{{ 'auth.login.title' | translate }}</h1>
        <p class="subtitle">{{ 'auth.login.subtitle' | translate }}</p>

        <form class="auth-form" (ngSubmit)="submit()">
          <label class="auth-field">
            <span class="auth-label">{{ 'auth.login.usernameLabel' | translate }}</span>
            <input
              class="text-input"
              name="username"
              [(ngModel)]="username"
              required
              autocomplete="username"
            />
          </label>

          <label class="auth-field">
            <span class="auth-label">{{ 'auth.login.passwordLabel' | translate }}</span>
            <input
              class="text-input"
              name="password"
              type="password"
              [(ngModel)]="password"
              required
              autocomplete="current-password"
            />
          </label>

          <button class="btn" type="submit" [disabled]="submitting" style="margin-top: 14px">
            {{ (submitting ? 'auth.login.submitting' : 'auth.login.submit') | translate }}
          </button>

          @if (emailNotVerified) {
            <div style="margin-top: 14px">
              <div class="auth-error" role="alert">
                {{ 'auth.login.emailNotVerified' | translate }}
              </div>
              <button
                class="btn"
                type="button"
                [disabled]="resendingVerification || verificationSent"
                (click)="resendVerification()"
                style="margin-top: 10px"
                [style.opacity]="verificationSent ? 0.6 : 1"
              >
                {{
                  (verificationSent
                    ? 'auth.login.resendSent'
                    : resendingVerification
                      ? 'auth.login.resendSending'
                      : 'auth.login.resendVerification'
                  ) | translate
                }}
              </button>
            </div>
          }

          @if (error) {
            <div class="auth-error" role="alert">{{ error }}</div>
          }
        </form>

        <p class="auth-alt">
          {{ 'auth.login.needAccount' | translate }}
          <a routerLink="/register">{{ 'auth.login.registerLink' | translate }}</a>
        </p>
      </div>
    </main>
  `,
})
export class LoginComponent {
  private readonly auth = inject(AuthService);
  private readonly router = inject(Router);
  private readonly translate = inject(TranslateService);

  username = '';
  password = '';
  error: string | null = null;
  submitting = false;
  emailNotVerified = false;
  resendingVerification = false;
  verificationSent = false;

  submit(): void {
    this.error = null;
    this.emailNotVerified = false;
    this.submitting = true;
    this.auth.login(this.username, this.password).subscribe({
      next: () => this.router.navigate(['/dashboard']),
      error: (err: HttpErrorResponse) => {
        if (err.status === 403 && err.error?.detail === 'Email not verified') {
          this.emailNotVerified = true;
        } else {
          this.error = err?.error?.detail || this.translate.t('auth.login.errorLoginFailed');
        }
        this.submitting = false;
      },
    });
  }

  resendVerification(): void {
    this.resendingVerification = true;
    this.verificationSent = false;
    this.auth.resendVerification(this.username).subscribe({
      next: () => {
        this.resendingVerification = false;
        this.verificationSent = true;
        setTimeout(() => (this.verificationSent = false), 3000);
      },
      error: (err: HttpErrorResponse) => {
        this.error = err?.error?.detail || this.translate.t('auth.login.errorResendFailed');
        this.resendingVerification = false;
      },
    });
  }
}

// frontend/react/src/pages/Login.tsx
import { useState } from "react";
import { useTranslation } from "react-i18next";
import { Link, useNavigate } from "react-router-dom";
import axios from "axios";
import api from "../api";
import { login } from "../auth";
import { AuthCard } from "../components/AuthCard";
import { apiErrorMessage } from "../utils/apiError";

export default function Login() {
  const { t } = useTranslation();
  const navigate = useNavigate();

  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [emailNotVerified, setEmailNotVerified] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [resendingVerification, setResendingVerification] = useState(false);
  const [verificationSent, setVerificationSent] = useState(false);

  const handleSubmit = async (e: React.SyntheticEvent<HTMLFormElement>) => {
    e.preventDefault();
    setError(null);
    setEmailNotVerified(false);
    setSubmitting(true);

    try {
      const { data } = await api.post("/auth/login", { username, password });

      login(data);

      navigate("/dashboard");
    } catch (err: unknown) {
      if (
        axios.isAxiosError(err) &&
        err.response?.status === 403 &&
        err.response?.data?.detail === "Email not verified"
      ) {
        setEmailNotVerified(true);
      } else {
        setError(
          apiErrorMessage(
            err,
            t("auth.login.errorLoginFailed"),
            t("auth.login.errorGeneric"),
          ),
        );
      }
    } finally {
      setSubmitting(false);
    }
  };

  const handleResendVerification = async () => {
    setResendingVerification(true);
    setVerificationSent(false);

    try {
      await api.post("/auth/resend-verification", { username });

      setVerificationSent(true);
      setTimeout(() => setVerificationSent(false), 3000);
    } catch (err: unknown) {
      setError(
        apiErrorMessage(
          err,
          t("auth.login.errorResendFailed"),
          t("auth.login.errorGeneric"),
        ),
      );
    } finally {
      setResendingVerification(false);
    }
  };

  return (
    <AuthCard title={t("auth.login.title")} subtitle={t("auth.login.subtitle")}>
      <form className="auth-form" onSubmit={handleSubmit}>
        <label className="auth-field">
          <span className="auth-label">{t("auth.login.usernameLabel")}</span>
          <input
            className="text-input"
            value={username}
            onChange={(e) => setUsername(e.target.value)}
            required
            autoComplete="username"
          />
        </label>

        <label className="auth-field">
          <span className="auth-label">{t("auth.login.passwordLabel")}</span>
          <input
            className="text-input"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            type="password"
            required
            autoComplete="current-password"
          />
        </label>

        <button
          className="btn"
          disabled={submitting}
          type="submit"
          style={{ marginTop: 14 }}
        >
          {submitting ? t("auth.login.submitting") : t("auth.login.submit")}
        </button>

        {emailNotVerified && (
          <div style={{ marginTop: 14 }}>
            <div className="auth-error" role="alert">
              {t("auth.login.emailNotVerified")}
            </div>
            <button
              className="btn"
              type="button"
              disabled={resendingVerification || verificationSent}
              onClick={handleResendVerification}
              style={{ marginTop: 10, opacity: verificationSent ? 0.6 : 1 }}
            >
              {verificationSent
                ? t("auth.login.resendSent")
                : resendingVerification
                  ? t("auth.login.resendSending")
                  : t("auth.login.resendVerification")}
            </button>
          </div>
        )}

        {error && (
          <div className="auth-error" role="alert">
            {error}
          </div>
        )}
      </form>

      <p className="auth-alt">
        {t("auth.login.needAccount")}{" "}
        <Link to="/register">{t("auth.login.registerLink")}</Link>
      </p>
    </AuthCard>
  );
}
