// frontend/angular/src/app/pages/training/training.component.ts
import { Component, ChangeDetectionStrategy, OnDestroy, OnInit, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { Subscription } from 'rxjs';
import {
  applyMove,
  applyUci,
  legalMoves,
  normalizeFen,
  pieceColorAt,
  sideToMove,
  START_FEN,
  Timeline,
  createTimeline,
  appendTimelineFen as coreAppendTimelineFen,
  jumpToIndex as coreJumpToIndex,
  isAtLatest,
  deriveStatus,
  splitOpeningLabel,
  deriveHintMarkers,
} from '@knight-school/chess-core';
import { BoardComponent, BoardArrow, BoardMarker } from './board.component';
import { TrainingItem, TrainingService } from '../../core/training.service';
import { FlipBoardButtonComponent } from '../../shared/flip-board-button.component';
import { SoundService } from '../../core/sound.service';
import { celebrateWin } from '../../lib/win-celebration';
import { TranslatePipe } from '../../core/i18n/translate.pipe';

const BLINK_CYCLE_MS = 420; // fadeIn(120) + hold(120) + fadeOut(180), matches react's useBlinkGreen

/**
 * Angular training page — mirror of react/src/pages/Training.tsx: a
 * board + right-rail layout with a move timeline (prev/next through the
 * plies actually played), a two-level hint, a status banner, and a brief
 * green blink on the just-played correct move.
 */
@Component({
  selector: 'app-training',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.Eager,
  imports: [FormsModule, BoardComponent, FlipBoardButtonComponent, TranslatePipe],
  template: `
    <main class="page">
      <div class="card">
        <div class="train">
          <div class="train-board-col">
            <div class="training-board-wrap">
              <app-board
                [position]="fen"
                [orientation]="orientation"
                [interactive]="true"
                [moveColor]="playerColor === 'b' ? 'black' : 'white'"
                [markers]="markers"
                [arrows]="arrows"
                [getLegalMoves]="getLegalMoves"
                [onMoveStart]="onMoveStart"
                [onMove]="onMove"
              ></app-board>
            </div>
            <div class="board-under">
              <span class="turn" [class.black]="!isWhiteToMove">
                <span class="turn-dot" aria-hidden="true"></span>
                {{ (isWhiteToMove ? 'training.whiteToMove' : 'training.blackToMove') | translate }}
              </span>
              <app-flip-board-button (flip)="flipBoard()" />
            </div>
          </div>

          <aside class="train-rail">
            <div class="rail-head">
              <div class="rail-eyebrow">{{ 'training.eyebrow' | translate }}</div>
              <div class="rail-title">
                <h1>{{ openingName }}</h1>
                @if (eco) {
                  <span class="eco-chip">{{ eco }}</span>
                }
              </div>
            </div>

            <div class="train-status {{ statusKind }}" role="status">
              <span class="train-status-ic" aria-hidden="true">{{ statusIcon }}</span>
              <div>
                <div class="train-status-msg">{{ statusMsg }}</div>
                @if (statusSub) {
                  <div class="train-status-sub">{{ statusSub }}</div>
                }
              </div>
            </div>

            @if (isSessionCompleted) {
              <div class="train-controls">
                <button
                  class="btn primary"
                  type="button"
                  (click)="trainAgain()"
                  [disabled]="isRestarting"
                >
                  {{ (isRestarting ? 'training.restarting' : 'training.trainAgain') | translate }}
                </button>
                <button class="btn" type="button" (click)="exit()">
                  {{ 'training.chooseAnother' | translate }}
                </button>
              </div>
            } @else {
              <div class="train-controls">
                <div class="train-stepper">
                  <button
                    class="btn"
                    type="button"
                    (click)="jumpToIndex(timeline.index - 1)"
                    [disabled]="busy || timeline.index <= 0"
                  >
                    {{ 'training.prev' | translate }}
                  </button>
                  <button
                    class="btn"
                    type="button"
                    (click)="jumpToIndex(timeline.index + 1)"
                    [disabled]="busy || timeline.index >= timeline.fens.length - 1"
                  >
                    {{ 'training.next' | translate }}
                  </button>
                </div>

                <button
                  class="btn hint"
                  type="button"
                  (click)="hint()"
                  [disabled]="busy || !itemId"
                  [attr.aria-label]="'training.showHint' | translate"
                  [title]="'training.showHint' | translate"
                >
                  💡
                </button>

                <form class="train-type-move" (ngSubmit)="onTextSubmit()">
                  <input
                    class="text-input"
                    name="moveInput"
                    [(ngModel)]="moveInput"
                    [placeholder]="'training.movePlaceholder' | translate"
                    [disabled]="isSubmitting"
                  />
                  <button
                    class="btn primary"
                    type="submit"
                    [disabled]="busy || !moveInput.trim() || !atLatest"
                    [title]="!atLatest ? ('training.jumpToLatest' | translate) : undefined"
                  >
                    {{ 'training.play' | translate }}
                  </button>
                </form>
              </div>
            }

            @if (!isSessionCompleted) {
              <button class="train-exit" type="button" (click)="exit()">
                {{ 'training.backToOpenings' | translate }}
              </button>
            }
          </aside>
        </div>
      </div>
    </main>
  `,
})
export class TrainingComponent implements OnInit, OnDestroy {
  private readonly route = inject(ActivatedRoute);
  private readonly router = inject(Router);
  private readonly training = inject(TrainingService);
  private readonly sound = inject(SoundService);

  sessionId = '';
  fen = START_FEN;
  itemId: string | null = null;
  correctMoveUci = '';
  playerColor: 'w' | 'b' = 'w';
  openingLabel = '';
  feedback = '';
  moveInput = '';
  isSubmitting = false;
  isAdvancing = false;
  isSessionCompleted = false;
  isRestarting = false;
  hintLevel = -1;
  wrongAttempts = 0;
  markers: BoardMarker[] = [];
  arrows: BoardArrow[] = [];
  orientation: 'white' | 'black' = 'white';

  timeline: Timeline = createTimeline(START_FEN);

  private blinkSquare: string | null = null;
  private blinkTimer: ReturnType<typeof setTimeout> | null = null;
  private autoplayedItemId: string | null = null;
  private advanceTimer: ReturnType<typeof setTimeout> | null = null;
  private paramSub?: Subscription;

  readonly onMove = (from: string, to: string): boolean => this.processMove(from, to);
  readonly onMoveStart = (square: string): boolean => this.canPickUp(square);
  readonly getLegalMoves = (square: string) => legalMoves(this.fen, square);

  get isWhiteToMove(): boolean {
    return sideToMove(this.fen) === 'w';
  }

  get isPlayerToMove(): boolean {
    return sideToMove(this.fen) === this.playerColor;
  }

  get atLatest(): boolean {
    return isAtLatest(this.timeline);
  }

  get busy(): boolean {
    return this.isSubmitting || this.isAdvancing;
  }

  // After 2 misses on this move, reveal the source-square hint; after 2 more
  // (4 total), reveal the target square too and draw an arrow to it. Derived
  // (not stored) so it only ever raises whatever the manual hint button set.
  private get effectiveHintLevel(): number {
    return Math.max(
      this.hintLevel,
      this.wrongAttempts >= 4 ? 1 : this.wrongAttempts >= 2 ? 0 : -1,
    );
  }

  private get openingParts() {
    return splitOpeningLabel(this.openingLabel);
  }

  get eco(): string {
    return this.openingParts.eco;
  }

  get openingName(): string {
    return this.openingParts.openingName;
  }

  private get status() {
    return deriveStatus({
      isSessionCompleted: this.isSessionCompleted,
      feedback: this.feedback,
      hintLevel: this.effectiveHintLevel,
      isPlayerToMove: this.isPlayerToMove,
      playerColor: this.playerColor,
    });
  }

  get statusKind(): string {
    return this.status.kind;
  }

  get statusIcon(): string {
    return this.status.icon;
  }

  get statusMsg(): string {
    return this.status.message;
  }

  get statusSub(): string {
    return this.status.sub;
  }

  ngOnInit(): void {
    // Subscribe (not snapshot) because trainAgain() navigates from one
    // /training/:id to another — same route config, so Angular reuses this
    // component instance rather than remounting it.
    this.paramSub = this.route.paramMap.subscribe((params) => {
      const id = params.get('id') ?? '';
      if (!id) return;
      this.sessionId = id;
      this.isRestarting = false;
      this.loadNext();
    });
  }

  ngOnDestroy(): void {
    this.paramSub?.unsubscribe();
    if (this.advanceTimer) clearTimeout(this.advanceTimer);
    if (this.blinkTimer) clearTimeout(this.blinkTimer);
  }

  private loadNext(): void {
    this.training.next(this.sessionId).subscribe({
      next: (item) => {
        this.applyItem(item);
        this.feedback = '';
        this.isSessionCompleted = false;
        this.resetTimeline(item.fen);
        this.maybeAutoplay();
        this.sound.play('gameStart');
      },
      error: () => {
        this.feedback = 'No more moves in this session or session expired.';
      },
    });
  }

  private applyItem(item: TrainingItem): void {
    this.itemId = item.itemId;
    this.fen = item.fen;
    this.openingLabel = item.openingLabel;
    this.correctMoveUci = item.correctMoveUci;
    this.playerColor = item.playerColor;
    this.orientation = item.playerColor === 'b' ? 'black' : 'white';
    this.hintLevel = -1;
    this.wrongAttempts = 0;
    this.updateMarkers();
  }

  private resetTimeline(fen: string): void {
    this.timeline = createTimeline(fen);
  }

  private appendTimelineFen(nextFen: string): void {
    this.timeline = coreAppendTimelineFen(this.timeline, nextFen);
  }

  jumpToIndex(nextIndex: number): void {
    const next = coreJumpToIndex(this.timeline, nextIndex);
    if (next === this.timeline) return;
    this.timeline = next;
    this.fen = this.timeline.fens[this.timeline.index] ?? this.timeline.fens[0];
    this.feedback = '';
    this.moveInput = '';
    this.hintLevel = -1;
    this.updateMarkers();
  }

  private maybeAutoplay(): void {
    if (!this.itemId || this.isSubmitting || this.isAdvancing) return;
    if (!this.correctMoveUci) return;
    if (this.autoplayedItemId === this.itemId) return;
    if (sideToMove(this.fen) === this.playerColor) return;

    this.autoplayedItemId = this.itemId;
    const uci = this.correctMoveUci;
    const preFen = this.fen;
    const applied = applyUci(this.fen, uci);
    if (applied) {
      this.fen = applied.nextFen;
      this.appendTimelineFen(applied.nextFen);
      this.sound.play('moveOpponent');
    }
    // Opponent's reply, not the player's turn — don't show the "Correct!" banner for it.
    this.submitMove(uci, preFen, { silent: true });
  }

  processMove(from: string, to: string): boolean {
    if (this.isSubmitting || this.isAdvancing || !this.itemId) return false;
    if (!from || !to || from === to) return false;

    const preFen = this.fen;
    const result = applyMove(this.fen, from, to, this.correctMoveUci);
    if (!result) {
      this.sound.play('illegal');
      this.feedback = '❌ Illegal move';
      return false;
    }

    this.fen = result.nextFen;
    this.appendTimelineFen(result.nextFen);
    this.feedback = '';
    this.moveInput = result.uci;
    this.submitMove(result.uci, preFen);
    this.sound.play(this.sound.getMoveSound(preFen, result.uci));
    return true;
  }

  private canPickUp(square: string): boolean {
    if (!this.atLatest) return false;
    if (this.isSubmitting || this.isAdvancing || !this.itemId) return false;
    if (!this.isPlayerToMove) return false;
    return pieceColorAt(this.fen, square) === this.playerColor;
  }

  private submitMove(uci: string, preFen: string, options: { silent?: boolean } = {}): void {
    if (!this.itemId) return;
    const silent = options.silent ?? false;
    const prevItemId = this.itemId;
    this.isSubmitting = true;

    this.training.submit(this.sessionId, this.itemId, uci).subscribe({
      next: (data) => {
        this.isSubmitting = false;

        if (data.correct) {
          if (!silent) {
            this.sound.play('correct');
            this.feedback = '✅ Correct!';
          }
          this.hintLevel = -1;
          this.wrongAttempts = 0;
          this.blinkGreen(uci, 2);

          if (data.fenAfter) {
            this.fen = normalizeFen(data.fenAfter);
          }

          if (data.sessionCompleted) {
            if (this.advanceTimer) {
              clearTimeout(this.advanceTimer);
              this.advanceTimer = null;
            }
            this.sound.play('achievement');
            celebrateWin();
            this.feedback = '✅ Session completed.';
            this.isSessionCompleted = true;
            this.isAdvancing = false;
            return;
          }

          this.isAdvancing = true;
          if (this.advanceTimer) clearTimeout(this.advanceTimer);
          this.advanceTimer = setTimeout(() => {
            this.training.next(this.sessionId).subscribe({
              next: (next) => {
                if (next.itemId === prevItemId) {
                  this.feedback = '✅ Opening complete.';
                  this.fen = next.fen;
                  this.openingLabel = next.openingLabel;
                  this.correctMoveUci = next.correctMoveUci;
                  this.playerColor = next.playerColor;
                  this.orientation = next.playerColor === 'b' ? 'black' : 'white';
                } else {
                  this.applyItem(next);
                  this.feedback = '';
                  this.isSessionCompleted = false;
                  this.resetTimeline(next.fen);
                  this.maybeAutoplay();
                }
                this.isAdvancing = false;
              },
              error: (err: { status?: number }) => {
                if (err?.status === 401) this.router.navigate(['/login']);
                this.feedback = 'No more moves in this session or session expired.';
                this.isAdvancing = false;
              },
            });
          }, 500);
          return;
        }

        // Incorrect: revert to the position that was actually submitted from.
        this.sound.play('incorrect');
        this.fen = preFen;
        this.resetTimeline(preFen);
        this.feedback = `❌ ${data.reason ?? 'Incorrect move'}`;
        if (!silent) {
          this.wrongAttempts += 1;
          this.updateMarkers();
        }
      },
      error: (err: { status?: number }) => {
        this.isSubmitting = false;
        if (err?.status === 401) this.router.navigate(['/login']);
        this.feedback = err?.status === 404 ? 'Session completed.' : 'Error submitting move';
      },
    });
  }

  onTextSubmit(): void {
    const uci = this.moveInput.trim();
    if (!uci || !this.atLatest) return;
    this.feedback = '';
    this.submitMove(uci, this.fen);
    this.moveInput = '';
  }

  hint(): void {
    if (this.isSubmitting || this.isAdvancing || !this.itemId) return;
    this.hintLevel = this.hintLevel < 0 ? 0 : 1;
    this.updateMarkers();
  }

  exit(): void {
    this.router.navigate(['/dashboard']);
  }

  trainAgain(): void {
    this.isRestarting = true;
    this.training.start(this.eco, this.openingName, this.playerColor).subscribe({
      next: (response) => {
        this.router.navigate(['/training', response.id]);
      },
      error: () => {
        this.isRestarting = false;
      },
    });
  }

  flipBoard(): void {
    this.orientation = this.orientation === 'white' ? 'black' : 'white';
  }

  private blinkGreen(uci: string, times: number): void {
    const toSquare = uci.slice(2, 4);
    if (!toSquare) return;

    if (this.blinkTimer) clearTimeout(this.blinkTimer);
    this.blinkSquare = toSquare;
    this.updateMarkers();

    this.blinkTimer = setTimeout(() => {
      this.blinkSquare = null;
      this.updateMarkers();
    }, times * BLINK_CYCLE_MS + 50);
  }

  private updateMarkers(): void {
    const effectiveHintLevel = this.effectiveHintLevel;
    const arr: BoardMarker[] = [];
    const hint = deriveHintMarkers(this.correctMoveUci, effectiveHintLevel, this.isSessionCompleted);
    if (hint) {
      arr.push({ square: hint.from, type: 'hint' });
      if (hint.to) arr.push({ square: hint.to, type: 'hint' });
    }
    if (this.blinkSquare) arr.push({ square: this.blinkSquare, type: 'blink' });
    this.markers = arr;

    // Arrow to the correct square once the deep hint (level 1) kicks in.
    this.arrows =
      effectiveHintLevel >= 1 && !this.isSessionCompleted && this.correctMoveUci
        ? [{ from: this.correctMoveUci.slice(0, 2), to: this.correctMoveUci.slice(2, 4), type: 'info' }]
        : [];
  }
}

// frontend/react/src/pages/Training.tsx
import React, {
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
} from "react";
import { useTranslation } from "react-i18next";
import { useNavigate, useParams } from "react-router-dom";
import api from "../api";
import Board, { type BoardArrow, type BoardMarker } from "../components/Board";
import { FlipBoardButton } from "../components/FlipBoardButton";
import {
  sideToMove,
  applyMove,
  applyUci,
  legalMoves,
  pieceColorAt,
  createTimeline,
  appendTimelineFen as coreAppendTimelineFen,
  jumpToIndex as coreJumpToIndex,
  isAtLatest,
  deriveStatus,
  splitOpeningLabel,
  deriveHintMarkers,
} from "@knight-school/chess-core";
import { useBlinkGreen } from "../hooks/useBlinkGreen";
import { useTrainingSession } from "../hooks/useTrainingSession";
import { useBoardOrientation } from "../hooks/useBoardOrientation";
import { usePreferences } from "../context/PreferencesContext";
import { getMoveSound, playSound } from "../utils/sound";
import { celebrateWin } from "../utils/winCelebration";

export const Training = () => {
  const { t } = useTranslation();
  const { id } = useParams();
  const navigate = useNavigate();

  const { blinkGreen, blinkSquare } = useBlinkGreen();
  const handle401 = useCallback(() => navigate("/login"), [navigate]);

  const {
    fen,
    setFen,
    itemId,
    correctMoveUci,
    playerColor,
    openingLabel,
    feedback,
    isSubmitting,
    isAdvancing,
    submitMove,
    takeAutoplayOnce,
    isSessionCompleted,
  } = useTrainingSession(id, handle401);

  const [moveInput, setMoveInput] = useState("");
  const { preferences } = usePreferences();
  const { orientation, flip, setOrientation } = useBoardOrientation();
  const [hintLevel, setHintLevel] = useState(-1);
  const [wrongAttempts, setWrongAttempts] = useState(0);
  const [lastMove, setLastMove] = useState<{ from: string; to: string } | null>(
    null,
  );
  const [localFeedback, setLocalFeedback] = useState("");
  const [isRestarting, setIsRestarting] = useState(false);
  const shownFeedback = localFeedback || feedback;

  // Only the autoplay effect below needs this: eslint's set-state-in-effect
  // rule flags an effect that reads reactive state directly and also calls
  // setState, so this one spot deliberately reads fen via a ref instead.
  const fenRef = useRef(fen);
  const lastSubmittedMoveUciRef = useRef<string>("");
  const lastAutoplayedItemIdRef = useRef<string | null>(null);
  const prevFeedbackRef = useRef<string>(feedback);
  const prevItemIdRef = useRef<string | null>(itemId);
  const pendingMoveRef = useRef<{ from: string; to: string } | null>(null);

  // Timeline: keep both state (for UI render) and a ref (for sync checks in effects)
  const [timeline, setTimeline] = useState(() => createTimeline(fen));
  const timelineRef = useRef(timeline);

  useEffect(() => {
    setTimeline((t) => {
      const current = t.fens[t.index];
      if (current === fen) return t;

      const next = createTimeline(fen);
      timelineRef.current = next;
      return next;
    });
  }, [fen]);

  useEffect(() => {
    timelineRef.current = timeline;
  }, [timeline]);

  useEffect(() => {
    fenRef.current = fen;
  }, [fen]);

  useEffect(() => {
    if (
      prevFeedbackRef.current !== "✅ Correct!" &&
      feedback === "✅ Correct!"
    ) {
      setHintLevel(-1);
      setWrongAttempts(0);
      if (pendingMoveRef.current) {
        setLastMove(pendingMoveRef.current);
        pendingMoveRef.current = null;
      }
    }
    prevFeedbackRef.current = feedback;
  }, [feedback]);

  // Count misses on the submit lifecycle (isSubmitting true -> false), not by
  // diffing feedback text: the backend always reports "❌ wrong move" for any
  // incorrect-but-legal move, so two different wrong tries in a row produce
  // identical feedback text and a text-diff would silently miss the second one.
  const prevIsSubmittingRef = useRef(isSubmitting);
  useEffect(() => {
    const wasSubmitting = prevIsSubmittingRef.current;
    prevIsSubmittingRef.current = isSubmitting;
    if (wasSubmitting && !isSubmitting && feedback.startsWith("❌")) {
      setWrongAttempts((n) => n + 1);
    }
  }, [isSubmitting, feedback]);

  // After 2 misses on this move, reveal the source-square hint; after 2 more
  // (4 total), reveal the target square too and draw an arrow to it. Derived
  // (not stored) so it only ever raises whatever the manual hint button set,
  // and never fights that button's own state via a second effect.
  const effectiveHintLevel = Math.max(
    hintLevel,
    wrongAttempts >= 4 ? 1 : wrongAttempts >= 2 ? 0 : -1,
  );

  useEffect(() => {
    if (feedback === "✅ Correct!" && lastSubmittedMoveUciRef.current) {
      blinkGreen(lastSubmittedMoveUciRef.current, 2);
    }
  }, [feedback, blinkGreen]);

  const prevSessionCompletedRef = useRef(isSessionCompleted);
  useEffect(() => {
    if (isSessionCompleted && !prevSessionCompletedRef.current) {
      celebrateWin();
    }
    prevSessionCompletedRef.current = isSessionCompleted;
  }, [isSessionCompleted]);

  const isPlayerToMove = useMemo(
    () => sideToMove(fen) === playerColor,
    [fen, playerColor],
  );
  const atLatest = isAtLatest(timeline);

  // Auto-orient the board to the trainee's color whenever a new session/item
  // loads — unless the user has locked orientation to a fixed side.
  useEffect(() => {
    if (preferences.board_orientation_mode === "auto") {
      setOrientation(playerColor === "b" ? "black" : "white");
    } else {
      setOrientation(preferences.board_orientation_mode);
    }
  }, [playerColor, preferences.board_orientation_mode, setOrientation]);

  const appendTimelineFen = useCallback((nextFen: string) => {
    setTimeline((t) => {
      const next = coreAppendTimelineFen(t, nextFen);
      timelineRef.current = next; // sync ref immediately
      return next;
    });
  }, []);

  const resetUiForJump = useCallback(() => {
    setLocalFeedback("");
    setMoveInput("");
    setHintLevel(-1);
    pendingMoveRef.current = null;
    setLastMove(null);
  }, []);

  // Reset per-item UI state when advancing to a new training item, without
  // remounting the board (a remount here would flash/reload cm-chessboard).
  useEffect(() => {
    if (prevItemIdRef.current !== itemId) {
      setLocalFeedback("");
      setMoveInput("");
      setHintLevel(-1);
      setWrongAttempts(0);
      setIsRestarting(false);
      pendingMoveRef.current = null;
    }
    prevItemIdRef.current = itemId;
  }, [itemId]);

  const jumpToIndex = useCallback(
    (nextIndex: number) => {
      const current = timelineRef.current;
      const next = coreJumpToIndex(current, nextIndex);
      if (next.index === current.index) return;

      const nextFen = next.fens[next.index] ?? next.fens[0];

      timelineRef.current = next;
      setTimeline(next);

      setFen(nextFen);
      resetUiForJump();
    },
    [resetUiForJump, setFen],
  );

  useEffect(() => {
    if (
      !id ||
      !itemId ||
      isSubmitting ||
      isAdvancing ||
      !correctMoveUci ||
      isSessionCompleted
    ) {
      return;
    }

    if (lastAutoplayedItemIdRef.current === itemId) {
      return;
    }
    // Critical: autoplay MUST only run when we're at the latest timeline position
    const tl = timelineRef.current;
    if (tl.index !== tl.fens.length - 1) {
      return;
    }
    if (sideToMove(fenRef.current) === playerColor) {
      return;
    }

    const can = takeAutoplayOnce(itemId);
    lastAutoplayedItemIdRef.current = itemId;
    lastSubmittedMoveUciRef.current = correctMoveUci;
    if (!can) return;

    // Play the opponent's reply locally to keep the timeline consistent.
    const uci = correctMoveUci;
    const applied = applyUci(fenRef.current, uci);
    if (applied) {
      appendTimelineFen(applied.nextFen);
      setLastMove({ from: uci.slice(0, 2), to: uci.slice(2, 4) });
      playSound("moveOpponent");
    }
    // Opponent's reply, not the player's turn — don't show the "Correct!" banner for it.
    void submitMove(uci, fenRef.current, { silent: true });
  }, [
    id,
    itemId,
    fen,
    correctMoveUci,
    playerColor,
    takeAutoplayOnce,
    submitMove,
    isSubmitting,
    isAdvancing,
    appendTimelineFen,
    isSessionCompleted,
  ]);

  const handleSubmit = async (e: React.SyntheticEvent) => {
    e.preventDefault();
    const uci = moveInput.trim();
    if (!uci) return;

    setLocalFeedback("");
    lastSubmittedMoveUciRef.current = uci;
    await submitMove(uci, fen);
    setMoveInput("");
  };

  const processMove = useCallback(
    (sourceSquare: string, targetSquare: string): boolean => {
      if (isSubmitting || isAdvancing || !itemId) return false;

      if (!sourceSquare || !targetSquare) return false;

      // ✅ prevent chess.js from being called with from===to
      if (sourceSquare === targetSquare) return false;

      const result = applyMove(fen, sourceSquare, targetSquare, correctMoveUci);
      if (!result) {
        playSound("illegal");
        setLocalFeedback("❌ Illegal move");
        return false;
      }
      setFen(result.nextFen);
      appendTimelineFen(result.nextFen);
      pendingMoveRef.current = { from: sourceSquare, to: targetSquare };

      setLocalFeedback("");
      lastSubmittedMoveUciRef.current = result.uci;
      setMoveInput(result.uci);
      void submitMove(result.uci, fen);
      const sound = getMoveSound(fen, result.uci);
      playSound(sound);
      return true;
    },
    [
      appendTimelineFen,
      correctMoveUci,
      fen,
      isAdvancing,
      isSubmitting,
      itemId,
      setFen,
      submitMove,
    ],
  );

  // Drag and click both funnel through cm-chessboard's move-input validation
  // into the same processMove (chess.js stays the source of truth).
  const onMove = useCallback(
    (from: string, to: string): boolean => {
      if (!from || !to || from === to) return false;
      return processMove(from, to);
    },
    [processMove],
  );

  // Whether the user may pick up the piece on `square` (mirrors the old
  // click/drag guards). Blocks past-timeline positions, in-flight submits,
  // non-white pieces, and off-turn moves.
  const canPickUp = useCallback(
    (square: string): boolean => {
      if (!atLatest) return false;
      if (isSubmitting || isAdvancing || !itemId) return false;
      if (!isPlayerToMove) return false;
      return pieceColorAt(fen, square) === playerColor;
    },
    [
      atLatest,
      fen,
      isAdvancing,
      isSubmitting,
      itemId,
      isPlayerToMove,
      playerColor,
    ],
  );

  // Legal targets for the picked-up piece — rendered as dots by cm-chessboard.
  const getLegalMoves = useCallback(
    (square: string): { to: string; promotion?: string }[] =>
      legalMoves(fen, square),
    [fen],
  );

  // Persistent highlights: hint (from, then from+to) and correct-move blink.
  const markers = useMemo((): BoardMarker[] => {
    const arr: BoardMarker[] = [];

    if (lastMove) {
      arr.push({ square: lastMove.from, type: "lastmove" });
      arr.push({ square: lastMove.to, type: "lastmove" });
    }

    const hint = deriveHintMarkers(
      correctMoveUci,
      effectiveHintLevel,
      isSessionCompleted,
    );
    if (hint) {
      arr.push({ square: hint.from, type: "hint" });
      if (hint.to) arr.push({ square: hint.to, type: "hint" });
    }

    if (blinkSquare) arr.push({ square: blinkSquare, type: "blink" });

    return arr;
  }, [correctMoveUci, effectiveHintLevel, blinkSquare, isSessionCompleted, lastMove]);

  // Arrow to the correct square once the deep hint (level 1) kicks in.
  const hintArrows = useMemo((): BoardArrow[] => {
    if (effectiveHintLevel < 1 || isSessionCompleted || !correctMoveUci) return [];
    return [
      { from: correctMoveUci.slice(0, 2), to: correctMoveUci.slice(2, 4), type: "info" },
    ];
  }, [effectiveHintLevel, isSessionCompleted, correctMoveUci]);

  // Split "C50 Italian Game" into an ECO chip + name for the rail header.
  const { eco, openingName } = splitOpeningLabel(openingLabel);

  // Derive the status banner from the existing feedback / turn / hint state.
  const status = deriveStatus({
    isSessionCompleted,
    feedback: shownFeedback,
    hintLevel: effectiveHintLevel,
    isPlayerToMove,
    playerColor,
  });
  const {
    kind: statusKind,
    icon: statusIcon,
    message: statusMsg,
    sub: statusSub,
  } = status;

  const busy = isSubmitting || isAdvancing;

  const trainAgain = useCallback(async () => {
    setIsRestarting(true);
    try {
      const response = await api.post("/training-sessions", {
        openingEco: eco,
        openingName,
        playerColor,
      });
      navigate(`/training/${response.data.id}`);
    } catch (error) {
      console.error("Error restarting session:", error);
      setIsRestarting(false);
    }
  }, [eco, openingName, playerColor, navigate]);

  return (
    <main className="page">
      <div className="card">
        <div className="train">
          <div className="train-board-col">
            <div className="training-board-wrap">
              <Board
                position={fen}
                orientation={orientation}
                interactive
                moveColor={playerColor === "b" ? "black" : "white"}
                markers={markers}
                arrows={hintArrows}
                getLegalMoves={getLegalMoves}
                onMoveStart={canPickUp}
                onMove={onMove}
              />
            </div>
            <div className="board-under">
              <span
                className={`turn${sideToMove(fen) === "w" ? "" : " black"}`}
              >
                <span className="turn-dot" aria-hidden="true" />
                {sideToMove(fen) === "w"
                  ? t("training.whiteToMove")
                  : t("training.blackToMove")}
              </span>
              <div className="board-toolbar">
                <FlipBoardButton className="icon-btn" onClick={flip} />
                <button
                  className="btn icon-btn hint-icon"
                  type="button"
                  onClick={() => {
                    if (
                      isSubmitting ||
                      isAdvancing ||
                      !itemId ||
                      isSessionCompleted
                    )
                      return;
                    setHintLevel((h) => (h < 0 ? 0 : 1));
                  }}
                  disabled={busy || !itemId || isSessionCompleted}
                  aria-label={t("training.showHint")}
                  title={t("training.showHint")}
                >
                  💡
                </button>
              </div>
            </div>
          </div>

          <aside className="train-rail">
            <div className="rail-head">
              <div className="rail-eyebrow">{t("training.eyebrow")}</div>
              <div className="rail-title">
                <h1>{openingName}</h1>
                {eco && <span className="eco-chip">{eco}</span>}
              </div>
            </div>

            <div className={`train-status ${statusKind}`} role="status">
              <span className="train-status-ic" aria-hidden="true">
                {statusIcon}
              </span>
              <div>
                <div className="train-status-msg">{statusMsg}</div>
                {statusSub && (
                  <div className="train-status-sub">{statusSub}</div>
                )}
              </div>
            </div>

            {isSessionCompleted ? (
              <div className="train-controls">
                <button
                  className="btn primary"
                  type="button"
                  onClick={trainAgain}
                  disabled={isRestarting}
                >
                  {isRestarting
                    ? t("training.restarting")
                    : t("training.trainAgain")}
                </button>
                <button
                  className="btn"
                  type="button"
                  onClick={() => navigate("/dashboard")}
                >
                  {t("training.chooseAnother")}
                </button>
              </div>
            ) : (
              <div className="train-controls">
                <div className="train-stepper">
                  <button
                    className="btn"
                    type="button"
                    onClick={() => jumpToIndex(timeline.index - 1)}
                    disabled={busy || timeline.index <= 0}
                  >
                    {t("training.prev")}
                  </button>
                  <button
                    className="btn"
                    type="button"
                    onClick={() => jumpToIndex(timeline.index + 1)}
                    disabled={
                      busy || timeline.index >= timeline.fens.length - 1
                    }
                  >
                    {t("training.next")}
                  </button>
                </div>

                <form className="train-type-move" onSubmit={handleSubmit}>
                  <input
                    className="text-input"
                    value={moveInput}
                    onChange={(e) => setMoveInput(e.target.value)}
                    placeholder={t("training.movePlaceholder")}
                    disabled={isSubmitting}
                  />
                  <button
                    className="btn primary"
                    type="submit"
                    disabled={busy || !moveInput.trim() || !atLatest}
                    title={!atLatest ? t("training.jumpToLatest") : undefined}
                  >
                    {t("training.play")}
                  </button>
                </form>
              </div>
            )}

            {!isSessionCompleted && (
              <button
                className="train-exit"
                type="button"
                onClick={() => navigate("/dashboard")}
              >
                {t("training.backToOpenings")}
              </button>
            )}
          </aside>
        </div>
      </div>
    </main>
  );
};
