// frontend/react/src/components/Board.tsx
import { useEffect, useRef, useState } from "react";
import { useTranslation } from "react-i18next";
import {
  Chessboard,
  COLOR,
  INPUT_EVENT_TYPE,
  BORDER_TYPE,
  type MoveInputEvent,
} from "cm-chessboard/src/Chessboard.js";
import {
  Markers,
  MARKER_TYPE,
} from "cm-chessboard/src/extensions/markers/Markers.js";
import { Accessibility } from "cm-chessboard/src/extensions/accessibility/Accessibility.js";
import {
  Arrows,
  ARROW_TYPE,
} from "cm-chessboard/src/extensions/arrows/Arrows.js";
import "cm-chessboard/assets/chessboard.css";
import "cm-chessboard/assets/extensions/markers/markers.css";
import "cm-chessboard/assets/extensions/arrows/arrows.css";
import "../../../packages/shared-styles/board.css";
import { usePreferences } from "../context/PreferencesContext";

// Sprites are served from react/public (copied from the cm-chessboard package).
const ASSETS_URL = "/cm-chessboard-assets/";

export type BoardMarkerKind = "hint" | "blink" | "lastmove";
export type BoardMarker = { square: string; type: BoardMarkerKind };
export type BoardArrow = {
  from: string;
  to: string;
  type?: keyof typeof ARROW_TYPE;
};

// Custom marker types (defined in styles/board.css). Kept as stable object
// references so removeMarkers(type) matches them by identity.
const CUSTOM_MARKER = {
  hint: { class: "marker-square-hint", slice: "markerSquare" },
  blink: { class: "marker-square-blink", slice: "markerSquare" },
  lastmove: { class: "marker-square-lastmove", slice: "markerSquare" },
} as const;

export type BoardProps = {
  /** Full FEN of the position to display. */
  position: string;
  orientation?: "white" | "black";
  /** Enable user move input (drag + click). Off = view-only preview. */
  interactive?: boolean;
  animated?: boolean;
  showCoordinates?: boolean;
  /** Which side the user is allowed to move. */
  moveColor?: "white" | "black";
  /** Persistent highlights (hints, correct-move blink). */
  markers?: BoardMarker[];
  /** Persistent arrows (e.g. suggested/best move). */
  arrows?: BoardArrow[];
  /** Legal targets for the square being picked up (shows dots). */
  getLegalMoves?: (square: string) => { to: string; promotion?: string }[];
  /** Return false to block picking up a piece on `square`. */
  onMoveStart?: (square: string) => boolean;
  /** Return true to accept the move, false to snap the piece back. */
  onMove?: (from: string, to: string) => boolean;
};

export default function Board({
  position,
  orientation = "white",
  interactive = false,
  animated,
  showCoordinates,
  moveColor = "white",
  markers,
  arrows,
  getLegalMoves,
  onMoveStart,
  onMove,
}: BoardProps) {
  const { preferences } = usePreferences();
  const boardTheme = preferences.board_theme;
  const pieceSet = preferences.piece_set;
  const effectiveShowCoordinates = showCoordinates ?? preferences.show_coordinates;
  const effectiveAnimated = animated ?? preferences.board_animations;
  const { i18n } = useTranslation();
  // The accessibility extension only ships piece-name translations for "de"
  // and "en" (falling back to "en" otherwise), so narrow our locale codes
  // (e.g. "en-US", "pt-BR") down to their base language.
  const accessibilityLanguage = i18n.language.slice(0, 2).toLowerCase();

  // Latches to true the first time this board becomes interactive, and never
  // goes back to false. This is what actually gates the Accessibility
  // extension's keyboard input / move-form (both constructor-only, see
  // below) — using the raw `interactive` prop instead would rebuild the
  // whole board (and refetch its piece sprites, since assetsCache is off)
  // on every toggle, which is disruptive for callers like Puzzles.tsx that
  // flip `interactive` off for the duration of each move submission.
  // Boards that are never interactive (preview cards) correctly never latch.
  const [prevInteractive, setPrevInteractive] = useState(interactive);
  const [keyboardCapable, setKeyboardCapable] = useState(interactive);
  if (interactive !== prevInteractive) {
    setPrevInteractive(interactive);
    if (interactive) setKeyboardCapable(true);
  }

  const hostRef = useRef<HTMLDivElement | null>(null);
  const boardRef = useRef<Chessboard | null>(null);
  // Bumped whenever the board instance below is destroyed and recreated, so
  // effects that operate on boardRef.current (move input, orientation,
  // position, markers) know to re-run against the new instance.
  const [boardVersion, setBoardVersion] = useState(0);

  // Keep the latest callbacks reachable from the single move-input handler,
  // which is registered once per interactive session.
  const cbRef = useRef({ getLegalMoves, onMoveStart, onMove });
  useEffect(() => {
    cbRef.current = { getLegalMoves, onMoveStart, onMove };
  });

  // Create the board once. Prop changes are applied by the effects below.
  useEffect(() => {
    const el = hostRef.current;
    if (!el) return;

    const board = new Chessboard(el, {
      position,
      orientation: orientation === "black" ? COLOR.black : COLOR.white,
      responsive: true,
      assetsUrl: ASSETS_URL,
      assetsCache: false,
      style: {
        cssClass: boardTheme,
        showCoordinates: effectiveShowCoordinates,
        borderType: BORDER_TYPE.none,
        pieces: { file: `pieces/${pieceSet}.svg` },
        animationDuration: effectiveAnimated ? 300 : 0,
      },
      extensions: [
        { class: Markers, props: { autoMarkers: MARKER_TYPE.frame } },
        { class: Arrows, props: {} },
        {
          class: Accessibility,
          props: {
            language: accessibilityLanguage,
            // Both are constructor-only and let an assistive-tech user act on
            // the board, so both are gated on `keyboardCapable`: a preview
            // board should describe the position (braille alt text, table,
            // piece list all stay on) without offering controls it can't
            // honor — the hidden move-piece form calls into cm-chessboard's
            // move-input callback, which is never set up on a non-interactive
            // board and throws if invoked.
            keyboardMoveInput: keyboardCapable,
            movePieceForm: keyboardCapable,
          },
        },
      ],
    });
    boardRef.current = board;
    setBoardVersion((v) => v + 1);

    return () => {
      board.destroy();
      boardRef.current = null;
    };
    // Position/orientation/move changes are applied by the effects below;
    // this effect only needs to re-run (destroy + recreate) when the
    // cosmetic style options (or keyboardCapable, which the Accessibility
    // extension's keyboardMoveInput/movePieceForm need at construction time)
    // change, since cm-chessboard's `style` and `extensions` are
    // constructor-only. keyboardCapable only ever flips false->true once, so
    // this doesn't churn on every `interactive` toggle.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [
    boardTheme,
    pieceSet,
    effectiveShowCoordinates,
    effectiveAnimated,
    accessibilityLanguage,
    keyboardCapable,
  ]);

  // Orientation (white/black at bottom).
  useEffect(() => {
    const board = boardRef.current;
    if (!board) return;
    const desired = orientation === "black" ? COLOR.black : COLOR.white;
    if (board.getOrientation() !== desired) {
      void board.setOrientation(desired, effectiveAnimated);
    }
  }, [orientation, effectiveAnimated, boardVersion]);

  // Position: only re-set when the piece placement actually changes, so an
  // accepted user move (already reflected on the board) does not re-animate.
  useEffect(() => {
    const board = boardRef.current;
    if (!board) return;
    const desired = position.split(" ")[0];
    const current = board.getPosition()?.split(" ")[0];
    if (desired !== current) void board.setPosition(position, effectiveAnimated);
  }, [position, effectiveAnimated, boardVersion]);

  // Enable/disable move input and register the handler.
  useEffect(() => {
    const board = boardRef.current;
    if (!board) return;

    if (!interactive) {
      board.disableMoveInput();
      return;
    }

    const handler = (event: MoveInputEvent): boolean | void => {
      const cb = cbRef.current;
      switch (event.type) {
        case INPUT_EVENT_TYPE.moveInputStarted: {
          const from = event.squareFrom ?? "";
          const allowed = cb.onMoveStart ? cb.onMoveStart(from) : true;
          if (allowed && cb.getLegalMoves) {
            board.removeLegalMovesMarkers();
            board.addLegalMovesMarkers(cb.getLegalMoves(from));
          }
          return allowed;
        }
        case INPUT_EVENT_TYPE.validateMoveInput: {
          board.removeLegalMovesMarkers();
          const to = event.squareTo ?? "";
          // Landing on a friendly piece is a re-selection, not a move attempt
          // (cm-chessboard makes it the new selection when we return false).
          // Skip onMove so callers don't flash illegal-move feedback.
          const ownPrefix = moveColor === "black" ? "b" : "w";
          if (board.getPiece(to)?.startsWith(ownPrefix)) return false;
          return cb.onMove ? cb.onMove(event.squareFrom ?? "", to) : false;
        }
        case INPUT_EVENT_TYPE.moveInputCanceled:
        case INPUT_EVENT_TYPE.moveInputFinished: {
          board.removeLegalMovesMarkers();
          return;
        }
        default:
          return;
      }
    };

    board.enableMoveInput(
      handler,
      moveColor === "black" ? COLOR.black : COLOR.white,
    );
    // Only disable if this is still the live board; when the component
    // unmounts or the board is recreated (style prop change), the creation
    // effect's cleanup may already have destroyed this instance.
    return () => {
      if (boardRef.current === board) board.disableMoveInput();
    };
  }, [interactive, moveColor, boardVersion]);

  // Persistent hint/blink markers. This layer owns only the custom marker
  // types, so it never disturbs the auto (selection) frame or legal-move dots.
  useEffect(() => {
    const board = boardRef.current;
    if (!board) return;
    board.removeMarkers(CUSTOM_MARKER.hint);
    board.removeMarkers(CUSTOM_MARKER.blink);
    board.removeMarkers(CUSTOM_MARKER.lastmove);
    for (const m of markers ?? []) {
      board.addMarker(CUSTOM_MARKER[m.type], m.square);
    }
  }, [markers, boardVersion]);

  // Persistent arrows (e.g. suggested/best move).
  useEffect(() => {
    const board = boardRef.current;
    if (!board) return;
    board.removeArrows();
    for (const a of arrows ?? []) {
      board.addArrow(ARROW_TYPE[a.type ?? "default"], a.from, a.to);
    }
  }, [arrows, boardVersion]);

  return <div ref={hostRef} className="board-host" />;
}

// frontend/angular/src/app/pages/training/board.component.ts
import {
  AfterViewInit,
  Component,
  ChangeDetectionStrategy,
  ElementRef,
  Input,
  OnChanges,
  OnDestroy,
  SimpleChanges,
  ViewChild,
} from '@angular/core';
import {
  Chessboard,
  COLOR,
  INPUT_EVENT_TYPE,
  BORDER_TYPE,
  MoveInputEvent,
} from 'cm-chessboard/src/Chessboard.js';
import {
  Markers,
  MARKER_TYPE,
} from 'cm-chessboard/src/extensions/markers/Markers.js';
import {
  Arrows,
  ARROW_TYPE,
} from 'cm-chessboard/src/extensions/arrows/Arrows.js';

// Sprites are served from angular/public (copied from the cm-chessboard package);
// the app is served under /angular/.
const ASSETS_URL = '/angular/cm-chessboard-assets/';

export type BoardMarkerKind = 'hint' | 'blink' | 'lastmove';
export interface BoardMarker {
  square: string;
  type: BoardMarkerKind;
}
export interface BoardArrow {
  from: string;
  to: string;
  type?: keyof typeof ARROW_TYPE;
}

// Custom marker types (styled in styles.css). Stable object refs so
// removeMarkers(type) matches them by identity.
const CUSTOM_MARKER: Record<
  BoardMarkerKind,
  { class: string; slice: string }
> = {
  hint: { class: 'marker-square-hint', slice: 'markerSquare' },
  blink: { class: 'marker-square-blink', slice: 'markerSquare' },
  lastmove: { class: 'marker-square-lastmove', slice: 'markerSquare' },
};

/**
 * Angular wrapper around cm-chessboard — the mirror of the React
 * `Board` component. Drag and click both funnel through `validateMoveInput`
 * into the `onMove` callback (chess.js stays the source of truth upstream).
 */
@Component({
  selector: 'app-board',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.Eager,
  template: `<div #host class="board-host"></div>`,
  styles: [
    `
      :host {
        display: block;
        width: 100%;
      }
    `,
  ],
})
export class BoardComponent implements AfterViewInit, OnChanges, OnDestroy {
  @ViewChild('host', { static: true })
  hostRef!: ElementRef<HTMLDivElement>;

  @Input() position = '';
  @Input() orientation: 'white' | 'black' = 'white';
  @Input() interactive = false;
  @Input() animated = true;
  @Input() showCoordinates = true;
  @Input() moveColor: 'white' | 'black' = 'white';
  @Input() markers: BoardMarker[] = [];
  @Input() arrows: BoardArrow[] = [];
  @Input() getLegalMoves?: (
    square: string,
  ) => { to: string; promotion?: string }[];
  @Input() onMoveStart?: (square: string) => boolean;
  @Input() onMove?: (from: string, to: string) => boolean;

  private board: Chessboard | null = null;

  ngAfterViewInit(): void {
    this.board = new Chessboard(this.hostRef.nativeElement, {
      position: this.position,
      orientation: this.orientation === 'black' ? COLOR.black : COLOR.white,
      responsive: true,
      assetsUrl: ASSETS_URL,
      style: {
        cssClass: 'default',
        showCoordinates: this.showCoordinates,
        borderType: BORDER_TYPE.none,
        animationDuration: this.animated ? 300 : 0,
      },
      extensions: [
        { class: Markers, props: { autoMarkers: MARKER_TYPE['frame'] } },
        { class: Arrows, props: {} },
      ],
    });
    if (this.interactive) this.enableInput();
    this.applyMarkers();
    this.applyArrows();
  }

  ngOnChanges(changes: SimpleChanges): void {
    const board = this.board;
    if (!board) return;

    if (changes['position']) {
      const desired = this.position.split(' ')[0];
      const current = board.getPosition()?.split(' ')[0];
      if (desired !== current) void board.setPosition(this.position, this.animated);
    }
    if (changes['orientation']) {
      const desired = this.orientation === 'black' ? COLOR.black : COLOR.white;
      if (board.getOrientation() !== desired) {
        void board.setOrientation(desired, false);
      }
    }
    if (changes['markers']) this.applyMarkers();
    if (changes['arrows']) this.applyArrows();
    if (changes['interactive'] || changes['moveColor']) {
      board.disableMoveInput();
      if (this.interactive) this.enableInput();
    }
  }

  ngOnDestroy(): void {
    this.board?.destroy();
    this.board = null;
  }

  private enableInput(): void {
    const board = this.board;
    if (!board) return;

    const handler = (event: MoveInputEvent): boolean | void => {
      switch (event.type) {
        case INPUT_EVENT_TYPE.moveInputStarted: {
          const from = event.squareFrom ?? '';
          const allowed = this.onMoveStart ? this.onMoveStart(from) : true;
          if (allowed && this.getLegalMoves) {
            board.removeLegalMovesMarkers();
            board.addLegalMovesMarkers(this.getLegalMoves(from));
          }
          return allowed;
        }
        case INPUT_EVENT_TYPE.validateMoveInput: {
          board.removeLegalMovesMarkers();
          const to = event.squareTo ?? '';
          // Landing on a friendly piece is a re-selection, not a move attempt.
          const ownPrefix = this.moveColor === 'black' ? 'b' : 'w';
          if (board.getPiece(to)?.startsWith(ownPrefix)) return false;
          return this.onMove ? this.onMove(event.squareFrom ?? '', to) : false;
        }
        case INPUT_EVENT_TYPE.moveInputCanceled:
        case INPUT_EVENT_TYPE.moveInputFinished:
          board.removeLegalMovesMarkers();
          return;
        default:
          return;
      }
    };

    board.enableMoveInput(
      handler,
      this.moveColor === 'black' ? COLOR.black : COLOR.white,
    );
  }

  private applyMarkers(): void {
    const board = this.board;
    if (!board) return;
    board.removeMarkers(CUSTOM_MARKER['hint']);
    board.removeMarkers(CUSTOM_MARKER['blink']);
    board.removeMarkers(CUSTOM_MARKER['lastmove']);
    for (const m of this.markers ?? []) {
      board.addMarker(CUSTOM_MARKER[m.type], m.square);
    }
  }

  private applyArrows(): void {
    const board = this.board;
    if (!board) return;
    board.removeArrows();
    for (const a of this.arrows ?? []) {
      board.addArrow(ARROW_TYPE[a.type ?? 'default'], a.from, a.to);
    }
  }
}
