// frontend/react/src/pages/Register.tsx
import { useState } from "react";
import { Trans, useTranslation } from "react-i18next";
import { Link } from "react-router-dom";
import api from "../api";
import { AuthCard } from "../components/AuthCard";
import { apiErrorMessage } from "../utils/apiError";

export default function Register() {
  const { t, i18n } = useTranslation();
  const [email, setEmail] = useState("");
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [passwordConfirm, setPasswordConfirm] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState(false);
  const [submitting, setSubmitting] = useState(false);

  const handleSubmit = async (e: React.SyntheticEvent<HTMLFormElement>) => {
    e.preventDefault();
    setError(null);

    if (password !== passwordConfirm) {
      setError(t("auth.register.passwordMismatch"));
      return;
    }

    setSubmitting(true);

    try {
      await api.post("/auth/register", {
        email,
        username,
        password,
        language: i18n.language,
      });
      setSuccess(true);
    } catch (err: unknown) {
      const genericError = t("auth.register.errorGeneric");
      setError(apiErrorMessage(err, genericError, genericError));
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <AuthCard
      title={t("auth.register.title")}
      subtitle={t("auth.register.subtitle")}
    >
      {success ? (
        <div>
          <p>
            <Trans
              i18nKey="auth.register.successMessage"
              values={{ email }}
              components={{ strong: <strong /> }}
            />
          </p>
          <p className="auth-alt" style={{ marginTop: 20 }}>
            <Link to="/login">{t("auth.register.returnToLogin")}</Link>
          </p>
        </div>
      ) : (
        <form className="auth-form" onSubmit={handleSubmit}>
          <label className="auth-field">
            <span className="auth-label">{t("auth.register.emailLabel")}</span>
            <input
              className="text-input"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              type="email"
              required
              autoComplete="email"
            />
            <span className="auth-hint">
              {t("auth.register.emailDisclaimer")}
            </span>
          </label>

          <label className="auth-field">
            <span className="auth-label">
              {t("auth.register.usernameLabel")}
            </span>
            <input
              className="text-input"
              value={username}
              onChange={(e) => setUsername(e.target.value)}
              required
              autoComplete="username"
            />
          </label>

          <label className="auth-field">
            <span className="auth-label">
              {t("auth.register.passwordLabel")}
            </span>
            <input
              className="text-input"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              type="password"
              required
              autoComplete="new-password"
            />
          </label>

          <label className="auth-field">
            <span className="auth-label">
              {t("auth.register.passwordConfirmLabel")}
            </span>
            <input
              className="text-input"
              value={passwordConfirm}
              onChange={(e) => setPasswordConfirm(e.target.value)}
              type="password"
              required
              autoComplete="new-password"
            />
          </label>

          <button
            className="btn"
            disabled={submitting}
            type="submit"
            style={{ marginTop: 6 }}
          >
            {submitting
              ? t("auth.register.submitting")
              : t("auth.register.submit")}
          </button>

          {error && (
            <div className="auth-error" role="alert">
              {error}
            </div>
          )}
        </form>
      )}

      <p className="auth-alt">
        {t("auth.register.haveAccount")}{" "}
        <Link to="/login">{t("auth.register.loginLink")}</Link>
      </p>
    </AuthCard>
  );
}

// frontend/angular/src/app/pages/register/register.component.ts
import { Component, ChangeDetectionStrategy, inject } from '@angular/core';
import { HttpErrorResponse } from '@angular/common/http';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { AuthService } from '../../core/auth.service';
import { TranslateService } from '../../core/i18n/translate.service';
import { TranslatePipe } from '../../core/i18n/translate.pipe';

@Component({
  selector: 'app-register',
  changeDetection: ChangeDetectionStrategy.Eager,
  imports: [FormsModule, RouterLink, TranslatePipe],
  template: `
    <main class="page">
      <div class="card">
        <h1 class="title">{{ 'auth.register.title' | translate }}</h1>
        <p class="subtitle">{{ 'auth.register.subtitle' | translate }}</p>

        @if (success) {
          <div>
            <p [innerHTML]="successHtml"></p>
            <p class="auth-alt" style="margin-top: 20px">
              <a routerLink="/login">{{ 'auth.register.returnToLogin' | translate }}</a>
            </p>
          </div>
        } @else {
          <form class="auth-form" (ngSubmit)="submit()">
            <label class="auth-field">
              <span class="auth-label">{{ 'auth.register.emailLabel' | translate }}</span>
              <input
                class="text-input"
                name="email"
                type="email"
                [(ngModel)]="email"
                required
                autocomplete="email"
              />
              <span class="auth-hint">{{ 'auth.register.emailDisclaimer' | translate }}</span>
            </label>

            <label class="auth-field">
              <span class="auth-label">{{ 'auth.register.usernameLabel' | translate }}</span>
              <input
                class="text-input"
                name="username"
                [(ngModel)]="username"
                required
                autocomplete="username"
              />
            </label>

            <label class="auth-field">
              <span class="auth-label">{{ 'auth.register.passwordLabel' | translate }}</span>
              <input
                class="text-input"
                name="password"
                type="password"
                [(ngModel)]="password"
                required
                autocomplete="new-password"
              />
            </label>

            <label class="auth-field">
              <span class="auth-label">{{
                'auth.register.passwordConfirmLabel' | translate
              }}</span>
              <input
                class="text-input"
                name="passwordConfirm"
                type="password"
                [(ngModel)]="passwordConfirm"
                required
                autocomplete="new-password"
              />
            </label>

            <button class="btn" type="submit" [disabled]="submitting" style="margin-top: 6px">
              {{ (submitting ? 'auth.register.submitting' : 'auth.register.submit') | translate }}
            </button>

            @if (error) {
              <div class="auth-error" role="alert">{{ error }}</div>
            }
          </form>
        }

        <p class="auth-alt">
          {{ 'auth.register.haveAccount' | translate }}
          <a routerLink="/login">{{ 'auth.register.loginLink' | translate }}</a>
        </p>
      </div>
    </main>
  `,
})
export class RegisterComponent {
  private readonly auth = inject(AuthService);
  private readonly translate = inject(TranslateService);

  email = '';
  username = '';
  password = '';
  passwordConfirm = '';
  error: string | null = null;
  success = false;
  submitting = false;
  successHtml = '';

  submit(): void {
    this.error = null;

    if (this.password !== this.passwordConfirm) {
      this.error = this.translate.t('auth.register.passwordMismatch');
      return;
    }

    this.submitting = true;
    this.auth
      .register(this.email, this.username, this.password, this.translate.lang())
      .subscribe({
        next: () => {
          this.successHtml = this.translate.t('auth.register.successMessage', {
            email: this.email,
          });
          this.success = true;
          this.submitting = false;
        },
        error: (err: HttpErrorResponse) => {
          this.error = err?.error?.detail || this.translate.t('auth.register.errorGeneric');
          this.submitting = false;
        },
      });
  }
}
