// react/src/pages/Training.tsx
import React, {
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
} from "react";
import { useNavigate, useParams } from "react-router-dom";
import Board, { type BoardMarker } from "../components/Board";
import { FlipBoardButton } from "../components/FlipBoardButton";
import {
  sideToMove,
  applyMove,
  applyUci,
  legalMoves,
  pieceColorAt,
  createTimeline,
  appendTimelineFen as coreAppendTimelineFen,
  jumpToIndex as coreJumpToIndex,
  isAtLatest,
  deriveStatus,
  splitOpeningLabel,
  deriveHintMarkers,
} from "@knight-school/chess-core";
import { useBlinkGreen } from "../hooks/useBlinkGreen";
import { useTrainingSession } from "../hooks/useTrainingSession";
import { useBoardOrientation } from "../hooks/useBoardOrientation";

export const Training = () => {
  const { id } = useParams();
  const navigate = useNavigate();

  const { blinkGreen, blinkSquare } = useBlinkGreen();
  const handle401 = useCallback(() => navigate("/login"), [navigate]);

  const {
    fen,
    setFen,
    itemId,
    correctMoveUci,
    openingLabel,
    feedback,
    isSubmitting,
    isAdvancing,
    submitMove,
    takeAutoplayOnce,
    isSessionCompleted,
  } = useTrainingSession(id, handle401);

  const [moveInput, setMoveInput] = useState("");
  const [showAnimations] = useState(true);
  const { orientation, flip } = useBoardOrientation();
  const [hintLevel, setHintLevel] = useState(-1);
  const [localFeedback, setLocalFeedback] = useState("");
  const shownFeedback = localFeedback || feedback;

  const fenRef = useRef(fen);
  const lastSubmittedMoveUciRef = useRef<string>("");
  const isSubmittingRef = useRef(isSubmitting);
  const isAdvancingRef = useRef(isAdvancing);
  const lastAutoplayedItemIdRef = useRef<string | null>(null);
  const prevFeedbackRef = useRef<string>(feedback);
  const prevItemIdRef = useRef<string | null>(itemId);

  // Timeline: keep both state (for UI render) and a ref (for sync checks in effects)
  const [timeline, setTimeline] = useState(() => createTimeline(fen));
  const timelineRef = useRef(timeline);

  useEffect(() => {
    setTimeline((t) => {
      const current = t.fens[t.index];
      if (current === fen) return t;

      const next = createTimeline(fen);
      timelineRef.current = next;
      return next;
    });
  }, [fen]);

  useEffect(() => {
    timelineRef.current = timeline;
  }, [timeline]);

  useEffect(() => {
    fenRef.current = fen;
  }, [fen]);

  useEffect(() => {
    isSubmittingRef.current = isSubmitting;
  }, [isSubmitting]);

  useEffect(() => {
    isAdvancingRef.current = isAdvancing;
  }, [isAdvancing]);

  useEffect(() => {
    if (
      prevFeedbackRef.current !== "✅ Correct!" &&
      feedback === "✅ Correct!"
    ) {
      setHintLevel(-1);
    }
    prevFeedbackRef.current = feedback;
  }, [feedback]);

  useEffect(() => {
    if (feedback === "✅ Correct!" && lastSubmittedMoveUciRef.current) {
      blinkGreen(lastSubmittedMoveUciRef.current, 2);
    }
  }, [feedback, blinkGreen]);

  const isWhiteToMove = useMemo(() => sideToMove(fen) === "w", [fen]);
  const atLatest = isAtLatest(timeline);

  const appendTimelineFen = useCallback((nextFen: string) => {
    setTimeline((t) => {
      const next = coreAppendTimelineFen(t, nextFen);
      timelineRef.current = next; // sync ref immediately
      return next;
    });
  }, []);

  const resetUiForJump = useCallback(() => {
    setLocalFeedback("");
    setMoveInput("");
    setHintLevel(-1);
  }, []);

  // Reset per-item UI state when advancing to a new training item, without
  // remounting the board (a remount here would flash/reload cm-chessboard).
  useEffect(() => {
    if (prevItemIdRef.current !== itemId) {
      setLocalFeedback("");
      setMoveInput("");
      setHintLevel(-1);
    }
    prevItemIdRef.current = itemId;
  }, [itemId]);

  const jumpToIndex = useCallback(
    (nextIndex: number) => {
      const current = timelineRef.current;
      const next = coreJumpToIndex(current, nextIndex);
      if (next.index === current.index) return;

      const nextFen = next.fens[next.index] ?? next.fens[0];

      timelineRef.current = next;
      setTimeline(next);

      setFen(nextFen);
      resetUiForJump();
    },
    [resetUiForJump, setFen],
  );

  useEffect(() => {
    if (
      !id ||
      !itemId ||
      isSubmitting ||
      isAdvancing ||
      !correctMoveUci ||
      isSessionCompleted
    ) {
      return;
    }

    if (lastAutoplayedItemIdRef.current === itemId) {
      return;
    }
    // Critical: autoplay MUST only run when we're at the latest timeline position
    const tl = timelineRef.current;
    if (tl.index !== tl.fens.length - 1) {
      return;
    }
    if (sideToMove(fenRef.current) !== "b") {
      return;
    }

    const can = takeAutoplayOnce(itemId);
    lastAutoplayedItemIdRef.current = itemId;
    lastSubmittedMoveUciRef.current = correctMoveUci;
    if (!can) return;

    // Play the opponent's reply locally to keep the timeline consistent.
    const uci = correctMoveUci;
    const applied = applyUci(fenRef.current, uci);
    if (applied) {
      appendTimelineFen(applied.nextFen);
    }
    // Opponent's reply, not the player's turn — don't show the "Correct!" banner for it.
    void submitMove(uci, fenRef.current, { silent: true });
  }, [
    id,
    itemId,
    fen,
    correctMoveUci,
    takeAutoplayOnce,
    submitMove,
    isSubmitting,
    isAdvancing,
    appendTimelineFen,
    isSessionCompleted,
  ]);

  const handleSubmit = async (e: React.SyntheticEvent) => {
    e.preventDefault();
    const uci = moveInput.trim();
    if (!uci) return;

    setLocalFeedback("");
    lastSubmittedMoveUciRef.current = uci;
    await submitMove(uci, fenRef.current);
    setMoveInput("");
  };

  const processMove = useCallback(
    (sourceSquare: string, targetSquare: string): boolean => {
      if (isSubmittingRef.current || isAdvancingRef.current || !itemId)
        return false;

      if (!sourceSquare || !targetSquare) return false;

      // ✅ prevent chess.js from being called with from===to
      if (sourceSquare === targetSquare) return false;

      const result = applyMove(
        fenRef.current,
        sourceSquare,
        targetSquare,
        correctMoveUci,
      );
      if (!result) {
        setLocalFeedback("❌ Illegal move");
        return false;
      }

      setFen(result.nextFen);
      appendTimelineFen(result.nextFen);

      setLocalFeedback("");
      lastSubmittedMoveUciRef.current = result.uci;
      setMoveInput(result.uci);
      void submitMove(result.uci, fenRef.current);

      return true;
    },
    [
      appendTimelineFen,
      correctMoveUci,
      itemId,
      setFen,
      submitMove,
    ],
  );

  // Drag and click both funnel through cm-chessboard's move-input validation
  // into the same processMove (chess.js stays the source of truth).
  const onMove = useCallback(
    (from: string, to: string): boolean => {
      if (!from || !to || from === to) return false;
      return processMove(from, to);
    },
    [processMove],
  );

  // Whether the user may pick up the piece on `square` (mirrors the old
  // click/drag guards). Blocks past-timeline positions, in-flight submits,
  // non-white pieces, and off-turn moves.
  const canPickUp = useCallback(
    (square: string): boolean => {
      if (!atLatest) return false;
      if (isSubmittingRef.current || isAdvancingRef.current || !itemId)
        return false;
      if (!isWhiteToMove) return false;
      return pieceColorAt(fenRef.current, square) === "w";
    },
    [atLatest, itemId, isWhiteToMove],
  );

  // Legal targets for the picked-up piece — rendered as dots by cm-chessboard.
  const getLegalMoves = useCallback(
    (square: string): { to: string; promotion?: string }[] =>
      legalMoves(fenRef.current, square),
    [],
  );

  // Persistent highlights: hint (from, then from+to) and correct-move blink.
  const markers = useMemo((): BoardMarker[] => {
    const arr: BoardMarker[] = [];

    const hint = deriveHintMarkers(correctMoveUci, hintLevel, isSessionCompleted);
    if (hint) {
      arr.push({ square: hint.from, type: "hint" });
      if (hint.to) arr.push({ square: hint.to, type: "hint" });
    }

    if (blinkSquare) arr.push({ square: blinkSquare, type: "blink" });

    return arr;
  }, [correctMoveUci, hintLevel, blinkSquare, isSessionCompleted]);

  // Split "C50 Italian Game" into an ECO chip + name for the rail header.
  const { eco, openingName } = splitOpeningLabel(openingLabel);

  // Derive the status banner from the existing feedback / turn / hint state.
  const status = deriveStatus({
    isSessionCompleted,
    feedback: shownFeedback,
    hintLevel,
    isWhiteToMove,
  });
  const { kind: statusKind, icon: statusIcon, message: statusMsg, sub: statusSub } = status;

  const busy = isSubmitting || isAdvancing;

  return (
    <main className="page">
      <div className="card">
        <div className="train">
          <div className="train-board-col">
            <div className="training-board-wrap">
              <Board
                position={fen}
                orientation={orientation}
                interactive
                animated={showAnimations}
                moveColor="white"
                markers={markers}
                getLegalMoves={getLegalMoves}
                onMoveStart={canPickUp}
                onMove={onMove}
              />
            </div>
            <div className="board-under">
              <span className={`turn${isWhiteToMove ? "" : " black"}`}>
                <span className="turn-dot" aria-hidden="true" />
                {isWhiteToMove ? "White to move" : "Black to move"}
              </span>
              <FlipBoardButton onClick={flip} />
              <button
                className="btn hint"
                type="button"
                onClick={() => {
                  if (
                    isSubmittingRef.current ||
                    isAdvancingRef.current ||
                    !itemId ||
                    isSessionCompleted
                  )
                    return;
                  setHintLevel((h) => (h < 0 ? 0 : 1));
                }}
                disabled={busy || !itemId || isSessionCompleted}
                aria-label="Show a hint"
                title="Show a hint"
              >
                💡
              </button>
            </div>
          </div>

          <aside className="train-rail">
            <div className="rail-head">
              <div className="rail-eyebrow">Training</div>
              <div className="rail-title">
                <h1>{openingName}</h1>
                {eco && <span className="eco-chip">{eco}</span>}
              </div>
            </div>

            <div className={`train-status ${statusKind}`} role="status">
              <span className="train-status-ic" aria-hidden="true">
                {statusIcon}
              </span>
              <div>
                <div className="train-status-msg">{statusMsg}</div>
                {statusSub && (
                  <div className="train-status-sub">{statusSub}</div>
                )}
              </div>
            </div>

            <div className="train-controls">
              <div className="train-stepper">
                <button
                  className="btn"
                  type="button"
                  onClick={() => jumpToIndex(timeline.index - 1)}
                  disabled={busy || timeline.index <= 0}
                >
                  ‹ Prev
                </button>
                <button
                  className="btn"
                  type="button"
                  onClick={() => jumpToIndex(timeline.index + 1)}
                  disabled={busy || timeline.index >= timeline.fens.length - 1}
                >
                  Next ›
                </button>
              </div>

              <form className="train-type-move" onSubmit={handleSubmit}>
                <input
                  className="text-input"
                  value={moveInput}
                  onChange={(e) => setMoveInput(e.target.value)}
                  placeholder="or type a move, e.g. e2e4"
                  disabled={isSubmitting}
                />
                <button
                  className="btn primary"
                  type="submit"
                  disabled={busy || !moveInput.trim() || !atLatest}
                  title={!atLatest ? "Jump to latest before submitting" : undefined}
                >
                  Play
                </button>
              </form>
            </div>

            <button
              className="train-exit"
              type="button"
              onClick={() => navigate("/dashboard")}
            >
              ← Back to openings
            </button>
          </aside>
        </div>
      </div>
    </main>
  );
};

// angular/src/app/pages/training/training.component.ts
import { Component, OnDestroy, OnInit, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import {
  applyMove,
  applyUci,
  legalMoves,
  normalizeFen,
  pieceColorAt,
  sideToMove,
  START_FEN,
  Timeline,
  createTimeline,
  appendTimelineFen as coreAppendTimelineFen,
  jumpToIndex as coreJumpToIndex,
  isAtLatest,
  deriveStatus,
  splitOpeningLabel,
  deriveHintMarkers,
} from '@knight-school/chess-core';
import { BoardComponent, BoardMarker } from './board.component';
import { TrainingItem, TrainingService } from '../../core/training.service';
import { FlipBoardButtonComponent } from '../../shared/flip-board-button.component';

const BLINK_CYCLE_MS = 420; // fadeIn(120) + hold(120) + fadeOut(180), matches react's useBlinkGreen

/**
 * Angular training page — mirror of react/src/pages/Training.tsx: a
 * board + right-rail layout with a move timeline (prev/next through the
 * plies actually played), a two-level hint, a status banner, and a brief
 * green blink on the just-played correct move.
 */
@Component({
  selector: 'app-training',
  standalone: true,
  imports: [FormsModule, BoardComponent, FlipBoardButtonComponent],
  template: `
    <main class="page">
      <div class="card">
        <div class="train">
          <div class="train-board-col">
            <div class="training-board-wrap">
              <app-board
                [position]="fen"
                [orientation]="orientation"
                [interactive]="true"
                moveColor="white"
                [markers]="markers"
                [getLegalMoves]="getLegalMoves"
                [onMoveStart]="onMoveStart"
                [onMove]="onMove"
              ></app-board>
            </div>
            <div class="board-under">
              <span class="turn" [class.black]="!isWhiteToMove">
                <span class="turn-dot" aria-hidden="true"></span>
                {{ isWhiteToMove ? 'White to move' : 'Black to move' }}
              </span>
              <app-flip-board-button (flip)="flipBoard()" />
            </div>
          </div>

          <aside class="train-rail">
            <div class="rail-head">
              <div class="rail-eyebrow">Training</div>
              <div class="rail-title">
                <h1>{{ openingName }}</h1>
                @if (eco) {
                  <span class="eco-chip">{{ eco }}</span>
                }
              </div>
            </div>

            <div class="train-status {{ statusKind }}" role="status">
              <span class="train-status-ic" aria-hidden="true">{{ statusIcon }}</span>
              <div>
                <div class="train-status-msg">{{ statusMsg }}</div>
                @if (statusSub) {
                  <div class="train-status-sub">{{ statusSub }}</div>
                }
              </div>
            </div>

            <div class="train-controls">
              <div class="train-stepper">
                <button
                  class="btn"
                  type="button"
                  (click)="jumpToIndex(timeline.index - 1)"
                  [disabled]="busy || timeline.index <= 0"
                >
                  ‹ Prev
                </button>
                <button
                  class="btn"
                  type="button"
                  (click)="jumpToIndex(timeline.index + 1)"
                  [disabled]="busy || timeline.index >= timeline.fens.length - 1"
                >
                  Next ›
                </button>
              </div>

              <button
                class="btn hint"
                type="button"
                (click)="hint()"
                [disabled]="busy || !itemId"
                aria-label="Show a hint"
                title="Show a hint"
              >
                💡
              </button>

              <form class="train-type-move" (ngSubmit)="onTextSubmit()">
                <input
                  class="text-input"
                  name="moveInput"
                  [(ngModel)]="moveInput"
                  placeholder="or type a move, e.g. e2e4"
                  [disabled]="isSubmitting"
                />
                <button
                  class="btn primary"
                  type="submit"
                  [disabled]="busy || !moveInput.trim() || !atLatest"
                  [title]="!atLatest ? 'Jump to latest before submitting' : undefined"
                >
                  Play
                </button>
              </form>
            </div>

            <button class="train-exit" type="button" (click)="exit()">← Back to openings</button>
          </aside>
        </div>
      </div>
    </main>
  `,
})
export class TrainingComponent implements OnInit, OnDestroy {
  private readonly route = inject(ActivatedRoute);
  private readonly router = inject(Router);
  private readonly training = inject(TrainingService);

  sessionId = '';
  fen = START_FEN;
  itemId: string | null = null;
  correctMoveUci = '';
  openingLabel = '';
  feedback = '';
  moveInput = '';
  isSubmitting = false;
  isAdvancing = false;
  isSessionCompleted = false;
  hintLevel = -1;
  markers: BoardMarker[] = [];
  orientation: 'white' | 'black' = 'white';

  timeline: Timeline = createTimeline(START_FEN);

  private blinkSquare: string | null = null;
  private blinkTimer: ReturnType<typeof setTimeout> | null = null;
  private autoplayedItemId: string | null = null;
  private advanceTimer: ReturnType<typeof setTimeout> | null = null;

  readonly onMove = (from: string, to: string): boolean => this.processMove(from, to);
  readonly onMoveStart = (square: string): boolean => this.canPickUp(square);
  readonly getLegalMoves = (square: string) => legalMoves(this.fen, square);

  get isWhiteToMove(): boolean {
    return sideToMove(this.fen) === 'w';
  }

  get atLatest(): boolean {
    return isAtLatest(this.timeline);
  }

  get busy(): boolean {
    return this.isSubmitting || this.isAdvancing;
  }

  private get openingParts() {
    return splitOpeningLabel(this.openingLabel);
  }

  get eco(): string {
    return this.openingParts.eco;
  }

  get openingName(): string {
    return this.openingParts.openingName;
  }

  private get status() {
    return deriveStatus({
      isSessionCompleted: this.isSessionCompleted,
      feedback: this.feedback,
      hintLevel: this.hintLevel,
      isWhiteToMove: this.isWhiteToMove,
    });
  }

  get statusKind(): string {
    return this.status.kind;
  }

  get statusIcon(): string {
    return this.status.icon;
  }

  get statusMsg(): string {
    return this.status.message;
  }

  get statusSub(): string {
    return this.status.sub;
  }

  ngOnInit(): void {
    this.sessionId = this.route.snapshot.paramMap.get('id') ?? '';
    if (this.sessionId) this.loadNext();
  }

  ngOnDestroy(): void {
    if (this.advanceTimer) clearTimeout(this.advanceTimer);
    if (this.blinkTimer) clearTimeout(this.blinkTimer);
  }

  private loadNext(): void {
    this.training.next(this.sessionId).subscribe({
      next: (item) => {
        this.applyItem(item);
        this.feedback = '';
        this.isSessionCompleted = false;
        this.resetTimeline(item.fen);
        this.maybeAutoplay();
      },
      error: () => {
        this.feedback = 'No more moves in this session or session expired.';
      },
    });
  }

  private applyItem(item: TrainingItem): void {
    this.itemId = item.itemId;
    this.fen = item.fen;
    this.openingLabel = item.openingLabel;
    this.correctMoveUci = item.correctMoveUci;
    this.hintLevel = -1;
    this.updateMarkers();
  }

  private resetTimeline(fen: string): void {
    this.timeline = createTimeline(fen);
  }

  private appendTimelineFen(nextFen: string): void {
    this.timeline = coreAppendTimelineFen(this.timeline, nextFen);
  }

  jumpToIndex(nextIndex: number): void {
    const next = coreJumpToIndex(this.timeline, nextIndex);
    if (next === this.timeline) return;
    this.timeline = next;
    this.fen = this.timeline.fens[this.timeline.index] ?? this.timeline.fens[0];
    this.feedback = '';
    this.moveInput = '';
    this.hintLevel = -1;
    this.updateMarkers();
  }

  private maybeAutoplay(): void {
    if (!this.itemId || this.isSubmitting || this.isAdvancing) return;
    if (!this.correctMoveUci) return;
    if (this.autoplayedItemId === this.itemId) return;
    if (sideToMove(this.fen) !== 'b') return;

    this.autoplayedItemId = this.itemId;
    const uci = this.correctMoveUci;
    const preFen = this.fen;
    const applied = applyUci(this.fen, uci);
    if (applied) {
      this.fen = applied.nextFen;
      this.appendTimelineFen(applied.nextFen);
    }
    // Opponent's reply, not the player's turn — don't show the "Correct!" banner for it.
    this.submitMove(uci, preFen, { silent: true });
  }

  processMove(from: string, to: string): boolean {
    if (this.isSubmitting || this.isAdvancing || !this.itemId) return false;
    if (!from || !to || from === to) return false;

    const preFen = this.fen;
    const result = applyMove(this.fen, from, to, this.correctMoveUci);
    if (!result) {
      this.feedback = '❌ Illegal move';
      return false;
    }

    this.fen = result.nextFen;
    this.appendTimelineFen(result.nextFen);
    this.feedback = '';
    this.moveInput = result.uci;
    this.submitMove(result.uci, preFen);
    return true;
  }

  private canPickUp(square: string): boolean {
    if (!this.atLatest) return false;
    if (this.isSubmitting || this.isAdvancing || !this.itemId) return false;
    if (!this.isWhiteToMove) return false;
    return pieceColorAt(this.fen, square) === 'w';
  }

  private submitMove(uci: string, preFen: string, options: { silent?: boolean } = {}): void {
    if (!this.itemId) return;
    const silent = options.silent ?? false;
    const prevItemId = this.itemId;
    this.isSubmitting = true;

    this.training.submit(this.sessionId, this.itemId, uci).subscribe({
      next: (data) => {
        this.isSubmitting = false;

        if (data.correct) {
          if (!silent) this.feedback = '✅ Correct!';
          this.blinkGreen(uci, 2);

          if (data.fenAfter) {
            this.fen = normalizeFen(data.fenAfter);
          }

          if (data.sessionCompleted) {
            if (this.advanceTimer) {
              clearTimeout(this.advanceTimer);
              this.advanceTimer = null;
            }
            this.feedback = '✅ Session completed.';
            this.isSessionCompleted = true;
            this.isAdvancing = false;
            return;
          }

          this.isAdvancing = true;
          if (this.advanceTimer) clearTimeout(this.advanceTimer);
          this.advanceTimer = setTimeout(() => {
            this.training.next(this.sessionId).subscribe({
              next: (next) => {
                if (next.itemId === prevItemId) {
                  this.feedback = '✅ Opening complete.';
                  this.fen = next.fen;
                  this.openingLabel = next.openingLabel;
                  this.correctMoveUci = next.correctMoveUci;
                } else {
                  this.applyItem(next);
                  this.feedback = '';
                  this.isSessionCompleted = false;
                  this.resetTimeline(next.fen);
                  this.maybeAutoplay();
                }
                this.isAdvancing = false;
              },
              error: (err: { status?: number }) => {
                if (err?.status === 401) this.router.navigate(['/login']);
                this.feedback = 'No more moves in this session or session expired.';
                this.isAdvancing = false;
              },
            });
          }, 500);
          return;
        }

        // Incorrect: revert to the position that was actually submitted from.
        this.fen = preFen;
        this.resetTimeline(preFen);
        this.feedback = `❌ ${data.reason ?? 'Incorrect move'}`;
      },
      error: (err: { status?: number }) => {
        this.isSubmitting = false;
        if (err?.status === 401) this.router.navigate(['/login']);
        this.feedback = err?.status === 404 ? 'Session completed.' : 'Error submitting move';
      },
    });
  }

  onTextSubmit(): void {
    const uci = this.moveInput.trim();
    if (!uci || !this.atLatest) return;
    this.feedback = '';
    this.submitMove(uci, this.fen);
    this.moveInput = '';
  }

  hint(): void {
    if (this.isSubmitting || this.isAdvancing || !this.itemId) return;
    this.hintLevel = this.hintLevel < 0 ? 0 : 1;
    this.updateMarkers();
  }

  exit(): void {
    this.router.navigate(['/dashboard']);
  }

  flipBoard(): void {
    this.orientation = this.orientation === 'white' ? 'black' : 'white';
  }

  private blinkGreen(uci: string, times: number): void {
    const toSquare = uci.slice(2, 4);
    if (!toSquare) return;

    if (this.blinkTimer) clearTimeout(this.blinkTimer);
    this.blinkSquare = toSquare;
    this.updateMarkers();

    this.blinkTimer = setTimeout(() => {
      this.blinkSquare = null;
      this.updateMarkers();
    }, times * BLINK_CYCLE_MS + 50);
  }

  private updateMarkers(): void {
    const arr: BoardMarker[] = [];
    const hint = deriveHintMarkers(this.correctMoveUci, this.hintLevel, this.isSessionCompleted);
    if (hint) {
      arr.push({ square: hint.from, type: 'hint' });
      if (hint.to) arr.push({ square: hint.to, type: 'hint' });
    }
    if (this.blinkSquare) arr.push({ square: this.blinkSquare, type: 'blink' });
    this.markers = arr;
  }
}
