// frontend/react/src/pages/Puzzles.tsx
// react/src/pages/Puzzles.tsx
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useTranslation } from "react-i18next";
import { Link, useNavigate, useSearchParams } from "react-router-dom";
import { AxiosError } from "axios";
import api from "../api";
import Board, { type BoardArrow, type BoardMarker } from "../components/Board";
import { Button } from "../components/Button";
import { FlipBoardButton } from "../components/FlipBoardButton";
import { useBoardOrientation } from "../hooks/useBoardOrientation";
import { usePreferences } from "../context/PreferencesContext";
import {
  START_FEN,
  applyMove,
  classifyFeedback,
  deriveHintMarkers,
  legalMoves,
  pieceColorAt,
  sideToMove,
} from "@knight-school/chess-core";
import { getMoveSound, playSound } from "../utils/sound";
import { celebratePuzzleCorrect } from "../utils/winCelebration";
import { formatThemeLabel } from "../utils/puzzleThemes";

type NextPuzzle = {
  puzzleId: string;
  fen: string;
  rating: number;
  themes?: string | null;
  correctMoveUci: string;
  lastMoveUci: string;
  moveIndex: number;
  solverMovesTotal: number;
};

export const Puzzles = () => {
  const { t } = useTranslation();
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const theme = searchParams.get("theme");

  type HistoryEntry = {
    puzzle: NextPuzzle;
    solved: boolean;
    usedHint: boolean;
    finalFen: string;
    finalLastMoveUci: string;
  };

  const [history, setHistory] = useState<HistoryEntry[]>([]);
  const [historyIndex, setHistoryIndex] = useState(-1);
  const historyRef = useRef(history);
  useEffect(() => {
    historyRef.current = history;
  }, [history]);
  const historyIndexRef = useRef(historyIndex);
  useEffect(() => {
    historyIndexRef.current = historyIndex;
  }, [historyIndex]);

  const atFrontier = historyIndex === history.length - 1;
  const viewingPast = !atFrontier && historyIndex >= 0;
  const currentEntry = viewingPast ? history[historyIndex] : null;

  // Set when loadNext hits a 404 (no puzzles due). Without this, puzzleId
  // would keep pointing at the previously-solved frontier entry, leaving the
  // board interactive on an already-completed position.
  const [frontierExhausted, setFrontierExhausted] = useState(false);

  const puzzleId =
    !frontierExhausted && atFrontier
      ? (history[historyIndex]?.puzzle.puzzleId ?? null)
      : null;
  const puzzleIdRef = useRef(puzzleId);
  useEffect(() => {
    puzzleIdRef.current = puzzleId;
  }, [puzzleId]);
  const [fen, setFen] = useState(START_FEN);
  const [correctMoveUci, setCorrectMoveUci] = useState("");
  const [lastMoveUci, setLastMoveUci] = useState("");
  const [moveIndex, setMoveIndex] = useState(0);
  const [solverMovesTotal, setSolverMovesTotal] = useState(1);
  const [rating, setRating] = useState<number | null>(null);
  const [themes, setThemes] = useState<string | null>(null);
  const [feedback, setFeedback] = useState("");
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [solved, setSolved] = useState(0);
  const [streak, setStreak] = useState(0);
  const [bestStreak, setBestStreak] = useState(0);
  const [noPuzzlesDue, setNoPuzzlesDue] = useState(false);
  const [puzzleComplete, setPuzzleComplete] = useState(false);
  const [hintLevel, setHintLevel] = useState(-1);
  const [wrongAttempts, setWrongAttempts] = useState(0);
  const effectiveHintLevel = Math.max(
    hintLevel,
    wrongAttempts >= 4 ? 1 : wrongAttempts >= 2 ? 0 : -1,
  );
  const nextButtonRef = useRef<HTMLButtonElement>(null);

  // Move focus to the "Next puzzle" button when it appears, so keyboard
  // users can advance without hunting for it. useEffect (not autoFocus,
  // which fires unconditionally on mount) keeps this scoped to the moment
  // the button is actually revealed.
  useEffect(() => {
    if (puzzleComplete) nextButtonRef.current?.focus();
  }, [puzzleComplete]);
  const { preferences } = usePreferences();
  const { orientation, flip, setOrientation } = useBoardOrientation();

  const fenRef = useRef(fen);
  useEffect(() => {
    fenRef.current = fen;
  }, [fen]);

  // Mirrored synchronously at every write site (not via a useEffect) so
  // submit() always reads the up-to-date value: an effect-based mirror
  // would lag behind DOM updates that tests (and users) can act on
  // immediately, causing the next submit() to send a stale moveIndex.
  const moveIndexRef = useRef(moveIndex);
  const updateMoveIndex = (next: number | ((prev: number) => number)) => {
    setMoveIndex((prev) => {
      const resolved = typeof next === "function" ? next(prev) : next;
      moveIndexRef.current = resolved;
      return resolved;
    });
  };

  // Sticky per-puzzle: true once the hint button has been clicked anywhere
  // in this puzzle's move sequence, sent on every attempt so the backend can
  // persist it even though intermediate correct moves never touch the DB.
  const usedHintRef = useRef(false);

  const isMountedRef = useRef(true);
  useEffect(() => {
    isMountedRef.current = true;
    return () => {
      isMountedRef.current = false;
    };
  }, []);

  const loadNext = useCallback(async () => {
    setFeedback("");
    setNoPuzzlesDue(false);
    setPuzzleComplete(false);
    setHintLevel(-1);
    usedHintRef.current = false;
    setWrongAttempts(0);
    setFrontierExhausted(false);
    try {
      const res = await api.get<NextPuzzle>("/puzzles/next", {
        params: {
          ...(theme ? { theme } : undefined),
          ...(puzzleIdRef.current ? { excludeId: puzzleIdRef.current } : undefined),
        },
      });
      if (!isMountedRef.current) return;
      setFen(res.data.fen);
      setCorrectMoveUci(res.data.correctMoveUci);
      setLastMoveUci(res.data.lastMoveUci);
      updateMoveIndex(res.data.moveIndex);
      setSolverMovesTotal(res.data.solverMovesTotal);
      setRating(res.data.rating);
      setThemes(res.data.themes ?? null);
      setHistory((prev) => [
        ...prev,
        {
          puzzle: res.data,
          solved: false,
          usedHint: false,
          finalFen: res.data.fen,
          finalLastMoveUci: res.data.lastMoveUci,
        },
      ]);
      setHistoryIndex((prev) => prev + 1);
      if (preferences.board_orientation_mode === "auto") {
        setOrientation(sideToMove(res.data.fen) === "b" ? "black" : "white");
      } else {
        setOrientation(preferences.board_orientation_mode);
      }
    } catch (err) {
      if (!isMountedRef.current) return;
      const e = err as AxiosError;
      if (e.response?.status === 401) {
        navigate("/login");
        return;
      }
      if (e.response?.status === 404) {
        setLastMoveUci("");
        setNoPuzzlesDue(true);
        setFrontierExhausted(true);
        setFeedback(
          theme ? t("puzzles.noPuzzlesForTheme") : t("puzzles.noPuzzlesDue"),
        );
        return;
      }
      setLastMoveUci("");
      setFeedback(t("puzzles.loadFailed"));
    }
  }, [navigate, preferences.board_orientation_mode, setOrientation, t, theme]);

  useEffect(() => {
    const run = async () => {
      await loadNext();
    };
    void run();
  }, [loadNext]);

  const submit = useCallback(
    async (moveUci: string, preFen: string) => {
      if (!puzzleId || isSubmitting) return;
      setIsSubmitting(true);
      try {
        const res = await api.post<{
          correct: boolean;
          reason: string;
          fenAfter?: string | null;
          puzzleComplete?: boolean | null;
          opponentReplyUci?: string | null;
          nextCorrectMoveUci?: string | null;
        }>(`/puzzles/${puzzleId}/attempts`, {
          moveUci,
          moveIndex: moveIndexRef.current,
          usedHint: usedHintRef.current,
        });
        if (!isMountedRef.current) return;

        if (res.data.correct && res.data.puzzleComplete) {
          playSound("puzzleCorrect");
          celebratePuzzleCorrect();
          setFeedback(t("puzzles.correct"));
          setSolved((n) => n + 1);
          setStreak((n) => {
            const next = n + 1;
            setBestStreak((best) => Math.max(best, next));
            return next;
          });
          setPuzzleComplete(true);
          setHistory((prev) => {
            const next = [...prev];
            const idx = next.length - 1;
            next[idx] = {
              ...next[idx],
              solved: true,
              usedHint: usedHintRef.current,
              finalFen: fenRef.current,
              finalLastMoveUci: moveUci,
            };
            return next;
          });
        } else if (res.data.correct) {
          // Correct, but more solver moves remain: apply the auto-played
          // opponent reply and keep the puzzle interactive.
          playSound("puzzleCorrect");
          setFeedback(t("puzzles.keepGoing"));
          if (res.data.fenAfter) setFen(res.data.fenAfter);
          if (res.data.opponentReplyUci) setLastMoveUci(res.data.opponentReplyUci);
          if (res.data.nextCorrectMoveUci) setCorrectMoveUci(res.data.nextCorrectMoveUci);
          setHintLevel(-1);
          setWrongAttempts(0);
          updateMoveIndex((n) => n + 1);
        } else {
          playSound("puzzleWrong");
          setFeedback(
            `❌ ${res.data.reason || t("puzzles.incorrectFallback")}`,
          );
          setFen(preFen); // snap back to the puzzle position
          setStreak(0);
          setWrongAttempts((n) => n + 1);
        }
      } catch (err) {
        if (!isMountedRef.current) return;
        const e = err as AxiosError;
        if (e.response?.status === 401) navigate("/login");
        setFeedback(t("puzzles.submitError"));
      } finally {
        if (isMountedRef.current) setIsSubmitting(false);
      }
    },
    [puzzleId, isSubmitting, navigate, t],
  );

  const skip = useCallback(() => {
    if (!puzzleId || isSubmitting) return;
    setStreak(0);
    void loadNext();
  }, [puzzleId, isSubmitting, loadNext]);

  const goToPrev = useCallback(() => {
    setHistoryIndex((idx) => Math.max(0, idx - 1));
  }, []);

  const goToNext = useCallback(() => {
    if (historyIndexRef.current < historyRef.current.length - 1) {
      setHistoryIndex((idx) => idx + 1);
    } else {
      void loadNext();
    }
  }, [loadNext]);

  // While viewing a past entry, rating/themes/progress/to-move should reflect
  // that entry's own puzzle, not the live frontier puzzle's current state.
  const displayRating = viewingPast ? (currentEntry?.puzzle.rating ?? null) : rating;
  const displayThemes = viewingPast ? (currentEntry?.puzzle.themes ?? null) : themes;
  const displayMoveIndex = viewingPast
    ? (currentEntry?.puzzle.moveIndex ?? 0)
    : moveIndex;
  const displaySolverMovesTotal = viewingPast
    ? (currentEntry?.puzzle.solverMovesTotal ?? 1)
    : solverMovesTotal;

  const solverColor = sideToMove(viewingPast ? (currentEntry?.puzzle.fen ?? fen) : fen);

  const { kind: feedbackKind, icon: feedbackIcon } = classifyFeedback(feedback);
  const statusKind = feedbackKind === "neutral" ? "your" : feedbackKind;
  // Puzzles keeps its own neutral icon (pawn) rather than deriveStatus's king.
  const statusIcon = feedbackKind === "neutral" ? "♟" : feedbackIcon;
  const statusMsg =
    (viewingPast ? "" : feedback) ||
    (puzzleId
      ? t(
          solverColor === "b"
            ? "puzzles.findBestMoveBlack"
            : "puzzles.findBestMoveWhite",
        )
      : "");

  const onMove = useCallback(
    (from: string, to: string): boolean => {
      if (isSubmitting || !puzzleId || from === to) return false;
      const preFen = fenRef.current;
      const result = applyMove(preFen, from, to, correctMoveUci);
      if (!result) {
        playSound("illegal");
        return false;
      }

      setFen(result.nextFen);

      const moveSound = getMoveSound(preFen, result.uci);
      playSound(moveSound);

      void submit(result.uci, preFen);
      return true;
    },
    [isSubmitting, puzzleId, correctMoveUci, submit],
  );
  
  const canPickUp = useCallback(
    (square: string): boolean => {
      if (isSubmitting || !puzzleId) return false;
      return pieceColorAt(fenRef.current, square) === solverColor;
    },
    [isSubmitting, puzzleId, solverColor],
  );

  const getLegalMoves = useCallback(
    (square: string) => legalMoves(fenRef.current, square),
    [],
  );

  const themeList = useMemo(
    () =>
      (displayThemes ?? "")
        .split(" ")
        .filter(Boolean)
        .map(formatThemeLabel),
    [displayThemes],
  );

  // Highlight the enemy's setup move (from/to) that produced this puzzle position.
  const markers = useMemo((): BoardMarker[] => {
    const arr: BoardMarker[] = [];
    const lastMove = viewingPast ? currentEntry?.finalLastMoveUci : lastMoveUci;
    if (lastMove && lastMove.length >= 4) {
      arr.push({ square: lastMove.slice(0, 2), type: "lastmove" });
      arr.push({ square: lastMove.slice(2, 4), type: "lastmove" });
    }
    if (viewingPast) return arr;
    const hint = deriveHintMarkers(correctMoveUci, effectiveHintLevel, puzzleComplete);
    if (hint) {
      arr.push({ square: hint.from, type: "hint" });
      if (hint.to) arr.push({ square: hint.to, type: "hint" });
    }
    return arr;
  }, [viewingPast, currentEntry, lastMoveUci, correctMoveUci, effectiveHintLevel, puzzleComplete]);

  const hintArrows = useMemo((): BoardArrow[] => {
    if (viewingPast || effectiveHintLevel < 1 || puzzleComplete || !correctMoveUci) return [];
    return [
      { from: correctMoveUci.slice(0, 2), to: correctMoveUci.slice(2, 4), type: "info" },
    ];
  }, [viewingPast, effectiveHintLevel, puzzleComplete, correctMoveUci]);

  // The idle "find the best move" prompt shows a plain pawn glyph, colored
  // to match the side actually solving the puzzle (Puzzles overrides
  // deriveStatus's white king icon with a pawn for exactly this state).
  const isBlackToFindMove = feedbackKind === "neutral" && solverColor === "b";

  const statusBanner = statusMsg && (
    <div className={`train-status ${statusKind}`} role="status">
      <span
        className={`train-status-ic${isBlackToFindMove ? " is-black-piece" : ""}`}
        aria-hidden="true"
      >
        {statusIcon}
      </span>
      <div>
        <div className="train-status-msg">{statusMsg}</div>
      </div>
    </div>
  );

  return (
    <main className="page">
      <div className="card">
        <div className="train puzzles-train">
          <div className="train-board-col">
            <div className="training-board-wrap">
              <Board
                position={viewingPast ? currentEntry!.finalFen : fen}
                orientation={orientation}
                interactive={!viewingPast && !!puzzleId && !isSubmitting && !puzzleComplete}
                moveColor={solverColor === "b" ? "black" : "white"}
                markers={markers}
                arrows={hintArrows}
                onMoveStart={canPickUp}
                getLegalMoves={getLegalMoves}
                onMove={onMove}
              />
            </div>
            <div className="board-under">
              <span className={`turn${solverColor === "b" ? " black" : ""}`}>
                <span className="turn-dot" aria-hidden="true" />
                {solverColor === "b"
                  ? t("training.blackToMove")
                  : t("training.whiteToMove")}
              </span>
              <div className="board-toolbar">
                <FlipBoardButton className="icon-btn" onClick={flip} />
                {historyIndex > 0 && (
                  <Button
                    type="button"
                    variant="secondary"
                    className="icon-btn"
                    onClick={goToPrev}
                    aria-label={t("puzzles.previousPuzzle")}
                    title={t("puzzles.previousPuzzle")}
                  >
                    <span aria-hidden="true">⏮</span>
                  </Button>
                )}
                {!viewingPast && (
                  <Button
                    type="button"
                    variant="secondary"
                    className="icon-btn hint-icon"
                    onClick={() => {
                      if (!puzzleId || isSubmitting || puzzleComplete) return;
                      usedHintRef.current = true;
                      setHintLevel((h) => (h < 0 ? 0 : 1));
                    }}
                    disabled={!puzzleId || isSubmitting || puzzleComplete}
                    aria-label={t("puzzles.showHint")}
                    title={t("puzzles.showHint")}
                  >
                    <span aria-hidden="true">💡</span>
                  </Button>
                )}
                {puzzleId && !puzzleComplete && (
                  <Button
                    type="button"
                    variant="secondary"
                    className="icon-btn"
                    onClick={skip}
                    disabled={isSubmitting}
                    aria-label={t("puzzles.skipPuzzle")}
                    title={t("puzzles.skipPuzzle")}
                  >
                    <span aria-hidden="true">⏭</span>
                  </Button>
                )}
              </div>
            </div>
          </div>

          <div className="puzzle-status-slot">{statusBanner}</div>

          <aside className="train-rail puzzles-rail">
            <div className="rail-head">
              <div className="rail-eyebrow">{t("puzzles.eyebrow")}</div>
              <div className="rail-title">
                <h1>{t("puzzles.title")}</h1>
                {displayRating != null && (
                  <span className="eco-chip">
                    {t("puzzles.rating", { rating: displayRating })}
                  </span>
                )}
                {displaySolverMovesTotal > 1 && (
                  <span className="eco-chip">
                    {t("puzzles.moveProgress", {
                      current: displayMoveIndex + 1,
                      total: displaySolverMovesTotal,
                    })}
                  </span>
                )}
              </div>
            </div>

            <div className="puzzles-meta">
              <div className="puzzles-stats">
                <span className="stat-pill">
                  {t("puzzles.solved", { count: solved })}
                </span>
                <span
                  className={streak > 0 ? "stat-pill is-active" : "stat-pill"}
                >
                  {t("puzzles.streak", { count: streak })}
                  {streak > 0 ? " 🔥" : ""}
                  {bestStreak > 0
                    ? t("puzzles.streakBest", { best: bestStreak })
                    : ""}
                </span>
              </div>

              {theme && (
                <span className="stat-pill is-active">
                  {t("puzzles.practicing", { theme: formatThemeLabel(theme) })}
                </span>
              )}

              {themeList.length > 0 && (
                <div className="puzzles-themes">
                  {themeList.map((themeLabel) => (
                    <span key={themeLabel} className="puzzles-theme-chip">
                      {themeLabel}
                    </span>
                  ))}
                </div>
              )}
            </div>

            {((puzzleId && puzzleComplete) || viewingPast) && (
              <button
                ref={nextButtonRef}
                type="button"
                className="puzzles-next"
                onClick={goToNext}
              >
                {t("puzzles.nextPuzzle")}
              </button>
            )}

            {theme ? (
              <Link to="/puzzles" className="puzzles-back-link">
                {t("puzzles.backToDuePuzzles")}
              </Link>
            ) : (
              <Link to="/puzzles/themes" className="puzzles-back-link">
                {t("puzzles.browseThemes")}
              </Link>
            )}

            {noPuzzlesDue && !theme && (
              <Link to="/dashboard" className="puzzles-back-link">
                {t("puzzles.backToDashboard")}
              </Link>
            )}
          </aside>
        </div>
      </div>
    </main>
  );
};

export default Puzzles;

// frontend/angular/src/app/pages/puzzles/puzzles.component.ts
import { Component, ChangeDetectionStrategy, ElementRef, OnInit, ViewChild, inject } from '@angular/core';
import { Router, RouterLink } from '@angular/router';
import {
  START_FEN,
  applyMove,
  classifyFeedback,
  deriveHintMarkers,
  legalMoves,
  pieceColorAt,
  sideToMove,
} from '@knight-school/chess-core';
import { BoardArrow, BoardComponent, BoardMarker } from '../training/board.component';
import { FlipBoardButtonComponent } from '../../shared/flip-board-button.component';
import { NextPuzzle, PuzzlesService } from '../../core/puzzles.service';
import { SoundService } from '../../core/sound.service';
import { celebratePuzzleCorrect } from '../../lib/win-celebration';
import { formatThemeLabel } from '../../lib/puzzle-themes';
import { TranslateService } from '../../core/i18n/translate.service';
import { TranslatePipe } from '../../core/i18n/translate.pipe';

interface HistoryEntry {
  puzzle: NextPuzzle;
  solved: boolean;
  usedHint: boolean;
  finalFen: string;
  finalLastMoveUci: string;
}

/**
 * Angular puzzles page — mirror of react/src/pages/Puzzles.tsx: loads the
 * next due puzzle, lets the user drag a move on the board (or it snaps back
 * on a wrong answer), and tracks a solved count plus a current/best streak
 * with a Skip control so a stuck user isn't stranded.
 *
 * Also mirrors React's session-local history: every puzzle fetched this
 * session is kept in `history`, `historyIndex` can step backward through it
 * (read-only replay of a past puzzle's final position), and a hint button
 * escalates through two levels (dot -> arrow), auto-escalating after enough
 * wrong attempts. Clicking hint at all sets a sticky per-puzzle `usedHint`
 * flag sent with every attempt on that puzzle.
 */
@Component({
  selector: 'app-puzzles',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.Eager,
  imports: [BoardComponent, FlipBoardButtonComponent, RouterLink, TranslatePipe],
  template: `
    <main class="page">
      <div class="card">
        <div class="train puzzles-train">
          <div class="train-board-col">
            <div class="training-board-wrap">
              <app-board
                [position]="displayFen"
                [orientation]="orientation"
                [interactive]="!viewingPast && !!puzzleId && !isSubmitting && !puzzleComplete"
                [moveColor]="solverColor === 'b' ? 'black' : 'white'"
                [markers]="markers"
                [arrows]="arrows"
                [getLegalMoves]="getLegalMoves"
                [onMoveStart]="onMoveStart"
                [onMove]="onMove"
              ></app-board>
            </div>
            <div class="board-under">
              <span class="turn" [class.black]="solverColor === 'b'">
                <span class="turn-dot" aria-hidden="true"></span>
                {{ (solverColor === 'b' ? 'training.blackToMove' : 'training.whiteToMove') | translate }}
              </span>
              <div class="board-toolbar">
                <app-flip-board-button class="icon-btn" (flip)="flipBoard()" />
                @if (historyIndex > 0) {
                  <button
                    type="button"
                    class="icon-btn"
                    (click)="goToPrev()"
                    [attr.aria-label]="'puzzles.previousPuzzle' | translate"
                    [attr.title]="'puzzles.previousPuzzle' | translate"
                  >
                    <span aria-hidden="true">⏮</span>
                  </button>
                }
                @if (!viewingPast) {
                  <button
                    type="button"
                    class="icon-btn hint-icon"
                    (click)="showHint()"
                    [disabled]="!puzzleId || isSubmitting || puzzleComplete"
                    [attr.aria-label]="'puzzles.showHint' | translate"
                    [attr.title]="'puzzles.showHint' | translate"
                  >
                    <span aria-hidden="true">💡</span>
                  </button>
                }
                @if (puzzleId && !puzzleComplete) {
                  <button
                    type="button"
                    class="icon-btn"
                    (click)="skip()"
                    [disabled]="isSubmitting"
                    [attr.aria-label]="'puzzles.skipPuzzle' | translate"
                    [attr.title]="'puzzles.skipPuzzle' | translate"
                  >
                    <span aria-hidden="true">⏭</span>
                  </button>
                }
              </div>
            </div>
          </div>

          <div class="puzzle-status-slot">
            @if (statusMsg) {
              <div class="train-status {{ statusKind }}" role="status">
                <span class="train-status-ic" [class.is-black-piece]="isBlackToFindMove" aria-hidden="true">
                  {{ statusIcon }}
                </span>
                <div>
                  <div class="train-status-msg">{{ statusMsg }}</div>
                </div>
              </div>
            }
          </div>

          <aside class="train-rail puzzles-rail">
            <div class="rail-head">
              <div class="rail-eyebrow">{{ 'puzzles.eyebrow' | translate }}</div>
              <div class="rail-title">
                <h1>{{ 'puzzles.title' | translate }}</h1>
                @if (displayRating !== null) {
                  <span class="eco-chip">{{ 'puzzles.rating' | translate: { rating: displayRating } }}</span>
                }
                @if (displaySolverMovesTotal > 1) {
                  <span class="eco-chip">{{
                    'puzzles.moveProgress'
                      | translate: { current: displayMoveIndex + 1, total: displaySolverMovesTotal }
                  }}</span>
                }
              </div>
            </div>

            <div class="puzzles-meta">
              <div class="puzzles-stats">
                <span class="stat-pill">{{ 'puzzles.solved' | translate: { count: solved } }}</span>
                <span class="stat-pill" [class.is-active]="streak > 0">
                  {{ 'puzzles.streak' | translate: { count: streak } }}{{ streak > 0 ? ' 🔥' : '' }}{{
                    bestStreak > 0 ? ('puzzles.streakBest' | translate: { best: bestStreak }) : ''
                  }}
                </span>
              </div>

              @if (themeList.length > 0) {
                <div class="puzzles-themes">
                  @for (themeLabel of themeList; track themeLabel) {
                    <span class="puzzles-theme-chip">{{ themeLabel }}</span>
                  }
                </div>
              }
            </div>

            @if ((puzzleId && puzzleComplete) || viewingPast) {
              <button #nextBtn type="button" class="puzzles-next" (click)="goToNext()">
                {{ 'puzzles.nextPuzzle' | translate }}
              </button>
            }

            <a routerLink="/puzzles/themes" class="puzzles-back-link">{{
              'puzzles.browseThemes' | translate
            }}</a>

            @if (noPuzzlesDue) {
              <a routerLink="/dashboard" class="puzzles-back-link">{{
                'puzzles.backToDashboard' | translate
              }}</a>
            }
          </aside>
        </div>
      </div>
    </main>
  `,
})
export class PuzzlesComponent implements OnInit {
  private readonly router = inject(Router);
  private readonly puzzles = inject(PuzzlesService);
  private readonly sound = inject(SoundService);
  private readonly translate = inject(TranslateService);

  @ViewChild('nextBtn') nextBtnRef?: ElementRef<HTMLButtonElement>;

  history: HistoryEntry[] = [];
  historyIndex = -1;
  frontierExhausted = false;

  fen = START_FEN;
  correctMoveUci = '';
  rating: number | null = null;
  themes: string | null = null;
  moveIndex = 0;
  solverMovesTotal = 1;
  lastMoveUci = '';

  feedback = '';
  isSubmitting = false;
  solved = 0;
  streak = 0;
  bestStreak = 0;
  noPuzzlesDue = false;
  puzzleComplete = false;
  orientation: 'white' | 'black' = 'white';
  markers: BoardMarker[] = [];
  arrows: BoardArrow[] = [];

  hintLevel = -1;
  wrongAttempts = 0;
  private usedHint = false;

  readonly onMove = (from: string, to: string): boolean => this.processMove(from, to);
  readonly onMoveStart = (square: string): boolean => this.canPickUp(square);
  readonly getLegalMoves = (square: string) => legalMoves(this.fen, square);

  get atFrontier(): boolean {
    return this.historyIndex === this.history.length - 1;
  }

  get viewingPast(): boolean {
    return !this.atFrontier && this.historyIndex >= 0;
  }

  get currentEntry(): HistoryEntry | null {
    return this.viewingPast ? (this.history[this.historyIndex] ?? null) : null;
  }

  get puzzleId(): string | null {
    if (this.frontierExhausted || !this.atFrontier || this.puzzleComplete) return null;
    return this.history[this.historyIndex]?.puzzle.puzzleId ?? null;
  }

  get effectiveHintLevel(): number {
    const attemptFloor = this.wrongAttempts >= 4 ? 1 : this.wrongAttempts >= 2 ? 0 : -1;
    return Math.max(this.hintLevel, attemptFloor);
  }

  get displayFen(): string {
    return this.viewingPast ? (this.currentEntry?.finalFen ?? this.fen) : this.fen;
  }

  get displayRating(): number | null {
    return this.viewingPast ? (this.currentEntry?.puzzle.rating ?? null) : this.rating;
  }

  get displayMoveIndex(): number {
    return this.viewingPast ? (this.currentEntry?.puzzle.moveIndex ?? 0) : this.moveIndex;
  }

  get displaySolverMovesTotal(): number {
    return this.viewingPast ? (this.currentEntry?.puzzle.solverMovesTotal ?? 1) : this.solverMovesTotal;
  }

  get solverColor(): string {
    return sideToMove(this.viewingPast ? (this.currentEntry?.puzzle.fen ?? this.fen) : this.fen);
  }

  get displayThemes(): string | null {
    return this.viewingPast ? (this.currentEntry?.puzzle.themes ?? null) : this.themes;
  }

  get themeList(): string[] {
    return (this.displayThemes ?? '').split(' ').filter(Boolean).map(formatThemeLabel);
  }

  private get feedbackKind(): string {
    return classifyFeedback(this.feedback).kind;
  }

  get isBlackToFindMove(): boolean {
    return this.feedbackKind === 'neutral' && this.solverColor === 'b';
  }

  get statusKind(): string {
    const kind = this.feedbackKind;
    return kind === 'neutral' ? 'your' : kind;
  }

  get statusIcon(): string {
    if (this.feedbackKind === 'neutral') return '♟';
    return classifyFeedback(this.feedback).icon;
  }

  get statusMsg(): string {
    if (this.viewingPast) return '';
    if (this.feedback) return this.feedback;
    if (!this.puzzleId) return '';
    return this.translate.t(
      this.solverColor === 'b' ? 'puzzles.findBestMoveBlack' : 'puzzles.findBestMoveWhite',
    );
  }

  ngOnInit(): void {
    this.loadNext();
  }

  flipBoard(): void {
    this.orientation = this.orientation === 'white' ? 'black' : 'white';
  }

  showHint(): void {
    if (!this.puzzleId || this.isSubmitting || this.puzzleComplete) return;
    this.usedHint = true;
    this.hintLevel = this.hintLevel < 0 ? 0 : 1;
    this.refreshOverlay();
  }

  goToPrev(): void {
    this.historyIndex = Math.max(0, this.historyIndex - 1);
    this.refreshOverlay();
  }

  goToNext(): void {
    if (this.historyIndex < this.history.length - 1) {
      this.historyIndex += 1;
      this.refreshOverlay();
    } else {
      this.loadNext();
    }
  }

  skip(): void {
    if (!this.puzzleId || this.isSubmitting) return;
    this.streak = 0;
    this.loadNext();
  }

  private loadNext(): void {
    this.feedback = '';
    this.noPuzzlesDue = false;
    this.puzzleComplete = false;
    this.hintLevel = -1;
    this.usedHint = false;
    this.wrongAttempts = 0;
    this.frontierExhausted = false;
    this.puzzles.next().subscribe({
      next: (data: NextPuzzle) => {
        this.fen = data.fen;
        this.correctMoveUci = data.correctMoveUci;
        this.lastMoveUci = data.lastMoveUci;
        this.moveIndex = data.moveIndex;
        this.solverMovesTotal = data.solverMovesTotal;
        this.rating = data.rating;
        this.themes = data.themes ?? null;
        this.history = [
          ...this.history,
          {
            puzzle: data,
            solved: false,
            usedHint: false,
            finalFen: data.fen,
            finalLastMoveUci: data.lastMoveUci,
          },
        ];
        this.historyIndex = this.history.length - 1;
        this.orientation = sideToMove(data.fen) === 'b' ? 'black' : 'white';
        this.refreshOverlay();
      },
      error: (err: { status?: number }) => {
        if (err?.status === 401) {
          this.router.navigate(['/login']);
          return;
        }
        if (err?.status === 404) {
          this.lastMoveUci = '';
          this.noPuzzlesDue = true;
          this.frontierExhausted = true;
          this.feedback = this.translate.t('puzzles.noPuzzlesDue');
          this.refreshOverlay();
          return;
        }
        this.feedback = this.translate.t('puzzles.loadFailed');
      },
    });
  }

  private processMove(from: string, to: string): boolean {
    if (this.isSubmitting || !this.puzzleId || from === to) return false;
    const preFen = this.fen;
    const result = applyMove(this.fen, from, to, this.correctMoveUci);
    if (!result) {
      this.sound.play('illegal');
      return false;
    }
    this.fen = result.nextFen;
    this.sound.play(this.sound.getMoveSound(preFen, result.uci));
    this.submit(result.uci, preFen);
    return true;
  }

  private canPickUp(square: string): boolean {
    if (this.isSubmitting || !this.puzzleId) return false;
    return pieceColorAt(this.fen, square) === this.solverColor;
  }

  private submit(uci: string, preFen: string): void {
    if (!this.puzzleId || this.isSubmitting) return;
    this.isSubmitting = true;

    this.puzzles.submit(this.puzzleId, uci, this.moveIndex, this.usedHint).subscribe({
      next: (data) => {
        this.isSubmitting = false;

        if (data.correct && data.puzzleComplete) {
          this.sound.play('puzzleCorrect');
          celebratePuzzleCorrect();
          this.feedback = this.translate.t('puzzles.correct');
          this.solved += 1;
          this.streak += 1;
          this.bestStreak = Math.max(this.bestStreak, this.streak);
          this.puzzleComplete = true;
          const idx = this.history.length - 1;
          this.history = this.history.map((h, i) =>
            i === idx
              ? { ...h, solved: true, usedHint: this.usedHint }
              : h,
          );
          this.refreshOverlay();
          queueMicrotask(() => this.nextBtnRef?.nativeElement.focus());
        } else if (data.correct) {
          this.sound.play('puzzleCorrect');
          this.feedback = this.translate.t('puzzles.keepGoing');
          if (data.fenAfter) this.fen = data.fenAfter;
          if (data.opponentReplyUci) this.lastMoveUci = data.opponentReplyUci;
          if (data.nextCorrectMoveUci) this.correctMoveUci = data.nextCorrectMoveUci;
          this.hintLevel = -1;
          this.wrongAttempts = 0;
          this.moveIndex += 1;
          this.refreshOverlay();
        } else {
          this.sound.play('puzzleWrong');
          this.feedback = `❌ ${data.reason || this.translate.t('puzzles.incorrectFallback')}`;
          this.fen = preFen;
          this.streak = 0;
          this.wrongAttempts += 1;
          this.refreshOverlay();
        }
      },
      error: (err: { status?: number }) => {
        this.isSubmitting = false;
        if (err?.status === 401) this.router.navigate(['/login']);
        this.feedback = this.translate.t('puzzles.submitError');
      },
    });
  }

  private refreshOverlay(): void {
    const markers: BoardMarker[] = [];
    const lastMove = this.viewingPast ? this.currentEntry?.finalLastMoveUci : this.lastMoveUci;
    if (lastMove && lastMove.length >= 4) {
      markers.push({ square: lastMove.slice(0, 2), type: 'lastmove' });
      markers.push({ square: lastMove.slice(2, 4), type: 'lastmove' });
    }
    if (!this.viewingPast) {
      const hint = deriveHintMarkers(this.correctMoveUci, this.effectiveHintLevel, this.puzzleComplete);
      if (hint) {
        markers.push({ square: hint.from, type: 'hint' });
        if (hint.to) markers.push({ square: hint.to, type: 'hint' });
      }
    }
    this.markers = markers;

    this.arrows =
      !this.viewingPast && this.effectiveHintLevel >= 1 && !this.puzzleComplete && this.correctMoveUci
        ? [{ from: this.correctMoveUci.slice(0, 2), to: this.correctMoveUci.slice(2, 4), type: 'info' }]
        : [];
  }
}
