// frontend/angular/src/app/pages/settings/settings.component.ts
import { Component, ChangeDetectionStrategy, inject } from '@angular/core';
import { Router } from '@angular/router';
import { applyMove, legalMoves, START_FEN } from '@knight-school/chess-core';
import { PreferencesStoreService } from '../../core/preferences-store.service';
import { TranslateService } from '../../core/i18n/translate.service';
import { TranslatePipe } from '../../core/i18n/translate.pipe';
import { BoardComponent } from '../training/board.component';
import { LanguageToggleComponent } from '../../shared/language-toggle.component';
import { SettingsToggleRowComponent } from '../../shared/settings-toggle-row.component';
import {
  SettingsRadioGroupComponent,
  SettingsRadioOption,
} from '../../shared/settings-radio-group.component';
import { BoardOrientationMode, BoardTheme, PieceSet, Theme } from '../../core/preferences';
import { SnowPreferenceService } from '../../core/snow-preference.service';
import { SoundService } from '../../core/sound.service';

const THEMES: Theme[] = ['light', 'dark', 'system'];
const BOARD_THEMES: BoardTheme[] = [
  'default',
  'default-contrast',
  'green',
  'blue',
  'chess-club',
  'chessboard-js',
  'black-and-white',
];
const PIECE_SETS: PieceSet[] = ['standard', 'staunty', 'merida', 'pirouetti', 'chessnut'];
const ORIENTATION_MODES: BoardOrientationMode[] = ['auto', 'white', 'black'];

/** Angular counterpart of react/src/pages/Settings.tsx. */
@Component({
  selector: 'app-settings',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.Eager,
  imports: [
    TranslatePipe,
    BoardComponent,
    LanguageToggleComponent,
    SettingsToggleRowComponent,
    SettingsRadioGroupComponent,
  ],
  template: `
    <main class="page">
      <div class="card settings-card">
        <button
          type="button"
          class="settings-back-button"
          (click)="goBack()"
          aria-label="Back"
        >
          <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
            <polyline points="15 18 9 12 15 6" />
          </svg>
          Back
        </button>
        <h1 class="title">{{ 'settings.title' | translate }}</h1>
        <p class="subtitle">{{ 'settings.subtitle' | translate }}</p>

        <section class="settings-section settings-section--preview">
          <span class="settings-row-label">{{ 'settings.previewLabel' | translate }}</span>
          <div class="settings-preview-board">
            <app-board
              [position]="previewFen"
              [orientation]="preferences().board_orientation_mode === 'black' ? 'black' : 'white'"
              [interactive]="true"
              [moveColor]="previewMoveColor()"
              [getLegalMoves]="previewGetLegalMoves"
              [onMove]="previewOnMove"
            />
          </div>
        </section>

        <section class="settings-section">
          <div class="settings-row">
            <span class="settings-row-label">{{ 'settings.languageLabel' | translate }}</span>
            <app-language-toggle />
          </div>
        </section>

        <section class="settings-section">
          <h2 class="settings-section-heading">{{ 'settings.appearance.heading' | translate }}</h2>

          <app-settings-radio-group
            name="theme"
            [ariaLabel]="'settings.appearance.themeLabel' | translate"
            [rowLabel]="'settings.appearance.themeLabel' | translate"
            [value]="preferences().theme"
            [options]="themeOptions()"
            (valueChange)="update({ theme: $any($event) })"
          />

          <label class="settings-row" for="settings-board-theme">
            <span class="settings-row-label">{{ 'settings.appearance.boardThemeLabel' | translate }}</span>
            <select
              id="settings-board-theme"
              class="text-input settings-select"
              [value]="preferences().board_theme"
              (change)="update({ board_theme: $any($event.target).value })"
            >
              @for (boardTheme of boardThemes; track boardTheme) {
                <option [value]="boardTheme">{{ ('settings.boardThemes.' + boardTheme) | translate }}</option>
              }
            </select>
          </label>

          <label class="settings-row" for="settings-piece-set">
            <span class="settings-row-label">{{ 'settings.appearance.pieceSetLabel' | translate }}</span>
            <select
              id="settings-piece-set"
              class="text-input settings-select"
              [value]="preferences().piece_set"
              (change)="update({ piece_set: $any($event.target).value })"
            >
              @for (pieceSet of pieceSets; track pieceSet) {
                <option [value]="pieceSet">{{ ('settings.pieceSets.' + pieceSet) | translate }}</option>
              }
            </select>
          </label>

          <app-settings-toggle-row
            [label]="'settings.appearance.showCoordinatesLabel' | translate"
            [checked]="preferences().show_coordinates"
            (checkedChange)="update({ show_coordinates: $event })"
          />

          <app-settings-toggle-row
            [label]="'settings.appearance.boardAnimationsLabel' | translate"
            [checked]="preferences().board_animations"
            (checkedChange)="update({ board_animations: $event })"
          />

          <app-settings-toggle-row
            [label]="'settings.appearance.soundLabel' | translate"
            [checked]="preferences().sound"
            (checkedChange)="update({ sound: $event })"
          />

          <app-settings-toggle-row
            [label]="'settings.appearance.snowLabel' | translate"
            [checked]="snowPreference.enabled()"
            (checkedChange)="snowPreference.setEnabled($event)"
          />
        </section>

        <section class="settings-section">
          <h2 class="settings-section-heading">{{ 'settings.boardOrientation.heading' | translate }}</h2>
          <app-settings-radio-group
            name="board-orientation-mode"
            [ariaLabel]="'settings.boardOrientation.heading' | translate"
            [stacked]="true"
            [value]="preferences().board_orientation_mode"
            [options]="orientationOptions()"
            (valueChange)="update({ board_orientation_mode: $any($event) })"
          />
        </section>

        <section class="settings-section settings-section--footer">
          <button type="button" class="btn btn-secondary" (click)="handleReset()">
            {{ 'settings.resetToDefaults' | translate }}
          </button>
        </section>
      </div>
    </main>
  `,
})
export class SettingsComponent {
  private readonly router = inject(Router);
  private readonly store = inject(PreferencesStoreService);
  private readonly translate = inject(TranslateService);
  private readonly sound = inject(SoundService);
  readonly snowPreference = inject(SnowPreferenceService);

  readonly preferences = this.store.preferences;
  readonly boardThemes = BOARD_THEMES;
  readonly pieceSets = PIECE_SETS;

  previewFen = START_FEN;

  readonly previewGetLegalMoves = (square: string) => legalMoves(this.previewFen, square);

  readonly previewOnMove = (from: string, to: string): boolean => {
    if (!from || !to || from === to) return false;
    const result = applyMove(this.previewFen, from, to, `${from}${to}q`);
    if (!result) return false;
    this.sound.play(this.sound.getMoveSound(this.previewFen, result.uci));
    this.previewFen = result.nextFen;
    return true;
  };

  previewMoveColor(): 'white' | 'black' {
    return this.previewFen.split(' ')[1] === 'b' ? 'black' : 'white';
  }

  themeOptions(): SettingsRadioOption[] {
    return THEMES.map((theme) => ({ value: theme, label: this.translate.t(`theme.${theme}`) }));
  }

  orientationOptions(): SettingsRadioOption[] {
    return ORIENTATION_MODES.map((mode) => ({
      value: mode,
      label: this.translate.t(`settings.boardOrientation.${mode}`),
    }));
  }

  update(partial: Parameters<PreferencesStoreService['update']>[0]): void {
    this.store.update(partial);
  }

  handleReset(): void {
    if (!window.confirm(this.translate.t('settings.resetConfirm'))) return;
    this.store.reset();
    this.snowPreference.setEnabled(false);
  }

  goBack(): void {
    const from = (history.state as { from?: string } | null)?.from ?? '/dashboard';
    this.router.navigateByUrl(from);
  }
}

// react/src/pages/Settings.tsx
import { useCallback, useState } from "react";
import { useTranslation } from "react-i18next";
import { useLocation, useNavigate } from "react-router-dom";
import { ChevronLeft } from "lucide-react";
import { usePreferences } from "../context/PreferencesContext";
import { useSnowPreference } from "../hooks/useSnowPreference";
import { useSound } from "../hooks/useSound";
import { getMoveSound } from "../utils/sound";
import { LanguageToggle } from "../components/LanguageToggle";
import { Button } from "../components/Button";
import { SettingsToggleRow } from "../components/SettingsToggleRow";
import { SettingsRadioGroup } from "../components/SettingsRadioGroup";
import Board from "../components/Board";
import { START_FEN, applyMove, legalMoves } from "@knight-school/chess-core";
import type {
  BoardOrientationMode,
  BoardTheme,
  PieceSet,
  Theme,
} from "../preferences";

const BOARD_THEMES: BoardTheme[] = [
  "default",
  "default-contrast",
  "green",
  "blue",
  "chess-club",
  "chessboard-js",
  "black-and-white",
];

const PIECE_SETS: PieceSet[] = [
  "standard",
  "staunty",
  "merida",
  "pirouetti",
  "chessnut",
];

export default function Settings() {
  const { t } = useTranslation();
  const navigate = useNavigate();
  const location = useLocation();
  const backTo = (location.state as { from?: string } | null)?.from ?? "/dashboard";
  const { preferences, update, reset } = usePreferences();
  const { snowEnabled, setSnowEnabled } = useSnowPreference();
  const { play } = useSound();
  const [previewFen, setPreviewFen] = useState(START_FEN);

  const previewGetLegalMoves = useCallback(
    (square: string) => legalMoves(previewFen, square),
    [previewFen],
  );

  const previewOnMove = useCallback(
    (from: string, to: string): boolean => {
      if (!from || !to || from === to) return false;
      const result = applyMove(previewFen, from, to, `${from}${to}q`);
      if (!result) return false;
      play(getMoveSound(previewFen, result.uci));
      setPreviewFen(result.nextFen);
      return true;
    },
    [previewFen, play],
  );

  const handleReset = useCallback(() => {
    if (!window.confirm(t("settings.resetConfirm"))) return;
    reset();
    setSnowEnabled(false);
  }, [reset, setSnowEnabled, t]);

  return (
    <main className="page">
      <div className="card settings-card">
        <button
          type="button"
          className="settings-back-button"
          onClick={() => navigate(backTo)}
          aria-label="Back"
        >
          <ChevronLeft size={18} aria-hidden="true" />
          Back
        </button>
        <h1 className="title">{t("settings.title")}</h1>
        <p className="subtitle">{t("settings.subtitle")}</p>

        <section className="settings-section settings-section--preview">
          <span className="settings-row-label">
            {t("settings.previewLabel")}
          </span>
          <div className="settings-preview-board">
            <Board
              position={previewFen}
              orientation={
                preferences.board_orientation_mode === "black"
                  ? "black"
                  : "white"
              }
              interactive
              moveColor={previewFen.split(" ")[1] === "b" ? "black" : "white"}
              getLegalMoves={previewGetLegalMoves}
              onMove={previewOnMove}
            />
          </div>
        </section>

        <section className="settings-section">
          <div className="settings-row">
            <span className="settings-row-label">
              {t("settings.languageLabel")}
            </span>
            <LanguageToggle />
          </div>
        </section>

        <section className="settings-section">
          <h2 className="settings-section-heading">
            {t("settings.appearance.heading")}
          </h2>

          <SettingsRadioGroup
            name="theme"
            ariaLabel={t("settings.appearance.themeLabel")}
            rowLabel={t("settings.appearance.themeLabel")}
            value={preferences.theme}
            options={(["light", "dark", "system"] as Theme[]).map((theme) => ({
              value: theme,
              label: t(`theme.${theme}`),
            }))}
            onChange={(theme) => update({ theme })}
          />

          <label className="settings-row" htmlFor="settings-board-theme">
            <span className="settings-row-label">
              {t("settings.appearance.boardThemeLabel")}
            </span>
            <select
              id="settings-board-theme"
              className="text-input settings-select"
              value={preferences.board_theme}
              onChange={(e) =>
                update({ board_theme: e.target.value as BoardTheme })
              }
            >
              {BOARD_THEMES.map((boardTheme) => (
                <option key={boardTheme} value={boardTheme}>
                  {t(`settings.boardThemes.${boardTheme}`)}
                </option>
              ))}
            </select>
          </label>

          <label className="settings-row" htmlFor="settings-piece-set">
            <span className="settings-row-label">
              {t("settings.appearance.pieceSetLabel")}
            </span>
            <select
              id="settings-piece-set"
              className="text-input settings-select"
              value={preferences.piece_set}
              onChange={(e) =>
                update({ piece_set: e.target.value as PieceSet })
              }
            >
              {PIECE_SETS.map((pieceSet) => (
                <option key={pieceSet} value={pieceSet}>
                  {t(`settings.pieceSets.${pieceSet}`)}
                </option>
              ))}
            </select>
          </label>

          <SettingsToggleRow
            label={t("settings.appearance.showCoordinatesLabel")}
            checked={preferences.show_coordinates}
            onChange={(checked) => update({ show_coordinates: checked })}
          />

          <SettingsToggleRow
            label={t("settings.appearance.boardAnimationsLabel")}
            checked={preferences.board_animations}
            onChange={(checked) => update({ board_animations: checked })}
          />

          <SettingsToggleRow
            label={t("settings.appearance.soundLabel")}
            checked={preferences.sound}
            onChange={(checked) => update({ sound: checked })}
          />

          <SettingsToggleRow
            label={t("settings.appearance.snowLabel")}
            checked={snowEnabled}
            onChange={setSnowEnabled}
          />
        </section>

        <section className="settings-section">
          <h2 className="settings-section-heading">
            {t("settings.boardOrientation.heading")}
          </h2>
          <SettingsRadioGroup
            name="board-orientation-mode"
            ariaLabel={t("settings.boardOrientation.heading")}
            stacked
            value={preferences.board_orientation_mode}
            options={(["auto", "white", "black"] as BoardOrientationMode[]).map(
              (mode) => ({
                value: mode,
                label: t(`settings.boardOrientation.${mode}`),
              }),
            )}
            onChange={(mode) => update({ board_orientation_mode: mode })}
          />
        </section>

        <section className="settings-section settings-section--footer">
          <Button variant="secondary" onClick={handleReset}>
            {t("settings.resetToDefaults")}
          </Button>
        </section>
      </div>
    </main>
  );
}
