// angular/src/app/pages/dashboard/board-preview.component.ts
import {
  Component,
  Input,
  ViewChild,
  ElementRef,
  AfterViewInit,
  OnChanges,
  OnDestroy,
  SimpleChanges,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { BoardComponent } from '../training/board.component';
import { uciListToMoves, previewFen } from '@knight-school/chess-core';
import { Opening } from '../../core/openings.service';

/**
 * Board preview panel with ply stepper. Displays the selected opening's
 * position at a given ply (move index), with buttons to step through the moves.
 */
@Component({
  selector: 'app-board-preview',
  standalone: true,
  imports: [CommonModule, BoardComponent],
  template: `
    <div class="boardPreview" #container>
      <div class="boardPreview-board" [style.width.px]="sizePx">
        <app-board
          *ngIf="opening"
          [position]="previewPosition"
          [interactive]="false"
          [showCoordinates]="false"
        ></app-board>
      </div>

      <div class="ply-stepper">
        <button
          type="button"
          class="ply-btn"
          [class.active]="selectedPly === 0"
          (click)="selectedPly = 0"
        >
          Start
        </button>

        <button
          *ngFor="let uci of moveList; let idx = index"
          type="button"
          class="ply-btn"
          [class.active]="selectedPly === idx + 1"
          [title]="'After ply ' + (idx + 1)"
          (click)="selectedPly = idx + 1"
        >
          {{ uci }}
        </button>
      </div>
    </div>
  `,
  styles: [],
})
export class BoardPreviewComponent
  implements AfterViewInit, OnChanges, OnDestroy
{
  @ViewChild('container') containerRef!: ElementRef<HTMLDivElement>;

  @Input({ required: true }) openings!: Opening[];
  @Input() selectedOpeningName: string | null = null;

  private _selectedPly = 0;
  sizePx = 280;
  opening: Opening | null = null;
  moveList: string[] = [];

  private resizeObserver: ResizeObserver | null = null;

  get selectedPly(): number {
    return this._selectedPly;
  }

  set selectedPly(value: number) {
    this._selectedPly = value;
  }

  get previewPosition(): string {
    return previewFen(this.opening, this._selectedPly);
  }

  ngAfterViewInit(): void {
    this.setupResizeObserver();
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['selectedOpeningName'] || changes['openings']) {
      this.updateOpening();
      this.updateMoveList();
      // Default to the final ply when the opening changes, so the preview
      // opens showing the completed line, not the start position.
      if (changes['selectedOpeningName']?.currentValue !== changes['selectedOpeningName']?.previousValue) {
        this._selectedPly = this.moveList.length;
      }
      return;
    }
    this.updateMoveList();
  }

  ngOnDestroy(): void {
    this.resizeObserver?.disconnect();
  }

  private setupResizeObserver(): void {
    const el = this.containerRef?.nativeElement;
    if (!el) return;

    this.resizeObserver = new ResizeObserver((entries) => {
      const entry = entries[0];
      if (!entry) return;

      const w = entry.contentRect.width;
      const scale = 0.85;
      this.sizePx = Math.max(180, Math.floor(w * scale));
    });

    this.resizeObserver.observe(el);
  }

  private updateOpening(): void {
    this.opening =
      this.openings.find((o) => o.name === this.selectedOpeningName) ?? null;
  }

  private updateMoveList(): void {
    this.moveList = uciListToMoves(this.opening?.uci_moves);
  }
}

// react/src/components/openings/BoardPreview.tsx
import { useEffect, useMemo, useRef, useState } from "react";
import Board from "../Board";
import { uciListToMoves, previewFen } from "@knight-school/chess-core";
import type { Opening } from "../../pages/Dashboard";

export default function BoardPreview({
  openings,
  selectedOpeningName,
  playerColor,
}: {
  openings: Opening[];
  selectedOpeningName: string | null;
  /** Which side to view the board from — follows the Play as White/Black toggle. */
  playerColor: "w" | "b";
}) {
  // Callers remount this via a `key` on the selected opening, so selectedPly
  // starts fresh for each newly previewed line — a ply index never leaks
  // from a longer line onto a shorter one. Default to the final ply so the
  // preview opens showing the completed line, not the start position.
  const [selectedPly, setSelectedPly] = useState(() => {
    const opening = openings.find((o) => o.name === selectedOpeningName);
    return uciListToMoves(opening?.uci_moves).length;
  });

  // Measure container width and use it for board sizing
  const containerRef = useRef<HTMLDivElement | null>(null);
  const [sizePx, setSizePx] = useState(280);

  useEffect(() => {
    const el = containerRef.current;
    if (!el) return;

    const ro = new ResizeObserver((entries) => {
      const entry = entries[0];
      if (!entry) return;

      const w = entry.contentRect.width;
      // leave some breathing room inside the container
      const scale = 0.85; // tweak: 0.95–0.98
      setSizePx(Math.max(180, Math.floor(w * scale)));
    });

    ro.observe(el);
    return () => ro.disconnect();
  }, []);

  const opening = useMemo(
    (): Opening | null =>
      openings.find((o) => o.name === selectedOpeningName) ?? null,
    [openings, selectedOpeningName],
  );

  const moveList = useMemo(
    () => uciListToMoves(opening?.uci_moves),
    [opening],
  );

  const previewPosition = useMemo(
    () => previewFen(opening, selectedPly),
    [opening, selectedPly],
  );

  const orientation = playerColor === "b" ? "black" : "white";

  return (
    <div className="boardPreview" ref={containerRef}>
      <div
        className="boardPreview-board"
        style={{ width: `${sizePx}px`, maxWidth: "100%" }}
      >
        <Board
          position={previewPosition}
          orientation={orientation}
          interactive={false}
          showCoordinates={false}
        />
      </div>

      <div className="ply-stepper">
        <button
          type="button"
          className={`ply-btn${selectedPly === 0 ? " active" : ""}`}
          onClick={() => setSelectedPly(0)}
        >
          Start
        </button>

        {moveList.map((uci, idx) => {
          const plyNumber = idx + 1;
          const isActive = selectedPly === plyNumber;

          return (
            <button
              key={`${uci}-${idx}`}
              type="button"
              className={`ply-btn${isActive ? " active" : ""}`}
              onClick={() => setSelectedPly(plyNumber)}
              title={`After ply ${plyNumber}`}
            >
              {uci}
            </button>
          );
        })}
      </div>
    </div>
  );
}
