// angular/src/app/pages/dashboard/variation-list.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Opening } from '../../core/openings.service';
import { variationLabelOf, groupVariations, subVariationLabelOf } from '../../lib/group-openings';
import type { VariationGroup } from '../../lib/group-openings';

/**
 * Level-2 list: the variations of a single base opening, as lightweight rows
 * (ECO chip + label). No per-row board — selecting a row drives the shared
 * preview panel. `rows` is expected to lead with the base's root line.
 *
 * Some bases have hundreds of variations, so rows sharing a sub-variation
 * (e.g. "Najdorf Variation, 6.Be3" / "…, 6.Bg5") are clustered under a
 * collapsible header instead of dumped as one flat list.
 */
@Component({
  selector: 'app-variation-list',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="variation-rows" role="list">
      <ng-container *ngFor="let g of groups; trackBy: trackByGroup">
        <!-- Single-row group: render as plain row -->
        <button
          *ngIf="g.rows.length === 1"
          type="button"
          role="listitem"
          class="variation-row"
          [class.selected]="selectedName === g.rows[0].name"
          [attr.aria-pressed]="selectedName === g.rows[0].name"
          (click)="pick.emit(g.rows[0])"
        >
          <span class="r-eco">{{ g.rows[0].eco }}</span>
          <span class="r-name">{{ variationLabelOf(g.rows[0].name) }}</span>
        </button>

        <!-- Multi-row group: collapsible -->
        <div *ngIf="g.rows.length > 1" class="variation-group">
          <button
            type="button"
            class="variation-group-header"
            (click)="toggle(g.label)"
            [attr.aria-expanded]="isOpen(g)"
          >
            <span class="vg-caret" aria-hidden="true">
              {{ isOpen(g) ? '▾' : '▸' }}
            </span>
            <span class="vg-label">{{ g.label }}</span>
            <span class="vg-count">{{ g.rows.length }}</span>
          </button>
          <div
            *ngIf="isOpen(g)"
            class="variation-group-rows"
            role="list"
          >
            <button
              *ngFor="let o of g.rows; trackBy: trackByRow"
              type="button"
              role="listitem"
              class="variation-row"
              [class.selected]="selectedName === o.name"
              [attr.aria-pressed]="selectedName === o.name"
              (click)="pick.emit(o)"
            >
              <span class="r-eco">{{ o.eco }}</span>
              <span class="r-name">{{ subVariationLabelOf(o.name) }}</span>
            </button>
          </div>
        </div>
      </ng-container>
    </div>
  `,
  styles: [],
})
export class VariationListComponent {
  @Input({ required: true }) rows!: Opening[];
  @Input() selectedName: string | null = null;
  @Output() pick = new EventEmitter<Opening>();

  variationLabelOf = variationLabelOf;
  subVariationLabelOf = subVariationLabelOf;

  protected expanded = new Set<string>();

  get groups(): VariationGroup[] {
    return groupVariations(this.rows);
  }

  toggle(label: string): void {
    if (this.expanded.has(label)) {
      this.expanded.delete(label);
    } else {
      this.expanded.add(label);
    }
  }

  isOpen(g: VariationGroup): boolean {
    return this.expanded.has(g.label) || g.rows.some(o => o.name === this.selectedName);
  }

  trackByGroup(index: number, g: VariationGroup): string {
    return g.label;
  }

  trackByRow(index: number, o: Opening): string {
    return o.eco + o.name;
  }
}

// react/src/components/openings/VariationList.tsx
import { useState } from "react";
import type { Opening } from "../../pages/Dashboard";
import {
  variationLabelOf,
  subVariationLabelOf,
  groupVariations,
} from "../../lib/groupOpenings";

function Row({
  o,
  label,
  selected,
  onPick,
}: {
  o: Opening;
  label: string;
  selected: boolean;
  onPick: (o: Opening) => void;
}) {
  return (
    <button
      type="button"
      role="listitem"
      className={`variation-row${selected ? " selected" : ""}`}
      onClick={() => onPick(o)}
      aria-pressed={selected}
    >
      <span className="r-eco">{o.eco}</span>
      <span className="r-name">{label}</span>
    </button>
  );
}

/**
 * Level-2 list: the variations of a single base opening, as lightweight rows
 * (ECO chip + label). No per-row board — selecting a row drives the shared
 * preview panel. `rows` is expected to lead with the base's root line.
 *
 * Some bases have hundreds of variations, so rows sharing a sub-variation
 * (e.g. "Najdorf Variation, 6.Be3" / "…, 6.Bg5") are clustered under a
 * collapsible header instead of dumped as one flat list.
 */
export default function VariationList({
  rows,
  selectedName,
  onPick,
}: {
  rows: Opening[];
  selectedName: string | null;
  onPick: (o: Opening) => void;
}) {
  const groups = groupVariations(rows);
  const [expanded, setExpanded] = useState<Set<string>>(new Set());

  const toggle = (label: string) =>
    setExpanded((prev) => {
      const next = new Set(prev);
      if (next.has(label)) next.delete(label);
      else next.add(label);
      return next;
    });

  return (
    <div className="variation-rows" role="list">
      {groups.map((g) => {
        if (g.rows.length === 1) {
          const o = g.rows[0];
          return (
            <Row
              key={o.eco + o.name}
              o={o}
              label={variationLabelOf(o.name)}
              selected={selectedName === o.name}
              onPick={onPick}
            />
          );
        }

        const containsSelected = g.rows.some((o) => o.name === selectedName);
        const open = expanded.has(g.label) || containsSelected;

        return (
          <div className="variation-group" key={g.label}>
            <button
              type="button"
              className="variation-group-header"
              onClick={() => toggle(g.label)}
              aria-expanded={open}
            >
              <span className="vg-caret" aria-hidden="true">
                {open ? "▾" : "▸"}
              </span>
              <span className="vg-label">{g.label}</span>
              <span className="vg-count">{g.rows.length}</span>
            </button>
            {open && (
              <div className="variation-group-rows" role="list">
                {g.rows.map((o) => (
                  <Row
                    key={o.eco + o.name}
                    o={o}
                    label={subVariationLabelOf(o.name)}
                    selected={selectedName === o.name}
                    onPick={onPick}
                  />
                ))}
              </div>
            )}
          </div>
        );
      })}
    </div>
  );
}
