// frontend/angular/src/app/shared/overflow-menu.component.ts
import {
  Component,
  ChangeDetectionStrategy,
  ElementRef,
  EventEmitter,
  Input,
  OnChanges,
  OnDestroy,
  Output,
  ViewChild,
  inject,
} from '@angular/core';
import { Router } from '@angular/router';
import { AuthService } from '../core/auth.service';
import { TranslatePipe } from '../core/i18n/translate.pipe';
import { ThemeToggleComponent } from './theme-toggle.component';
import { LanguageToggleComponent } from './language-toggle.component';

const APP_VERSION = 'dev';

const FOCUSABLE_SELECTOR =
  'a[href], button:not([disabled]), input:not([disabled]), [tabindex]:not([tabindex="-1"])';

/**
 * Angular counterpart of react/src/components/OverflowMenu.tsx — the
 * hamburger dropdown opened from HomeHeaderComponent. `.overflow-menu` is
 * `position: fixed` in header.css, so this renders in place rather than via
 * a true portal to `<body>` (React uses `createPortal` mainly to dodge
 * ancestor stacking/overflow, which doesn't apply here).
 */
@Component({
  selector: 'app-overflow-menu',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.Eager,
  imports: [TranslatePipe, ThemeToggleComponent, LanguageToggleComponent],
  template: `
    @if (open) {
      <div class="overflow-menu" (mousedown)="onBackdropMouseDown($event)">
        <nav
          class="overflow-menu-items"
          #menu
          role="dialog"
          aria-modal="true"
          [attr.aria-label]="'header.nav' | translate"
        >
          @if (auth.isLoggedIn) {
            <button class="overflow-menu-item" type="button" (click)="handleSettingsClick()">
              {{ 'header.settings' | translate }}
            </button>
            <button class="overflow-menu-item" type="button" (click)="handleLogout()">
              {{ 'header.logout' | translate }}
            </button>
          }
          <a
            class="overflow-menu-item"
            href="https://github.com/coliver/chess-trainer"
            target="_blank"
            rel="noopener noreferrer"
            (click)="closed.emit()"
          >
            {{ 'header.viewSource' | translate }}
          </a>
          <div class="overflow-menu-divider"></div>
          <div class="overflow-menu-control">
            <span class="overflow-menu-label">{{ 'language.toggle' | translate }}</span>
            <app-language-toggle />
          </div>
          <div class="overflow-menu-control">
            <span class="overflow-menu-label">{{ 'theme.toggle' | translate }}</span>
            <app-theme-toggle />
          </div>
          <div class="overflow-menu-divider"></div>
          <div class="overflow-menu-footer">
            <span class="overflow-menu-version">{{ appVersion }}</span>
          </div>
        </nav>
      </div>
    }
  `,
})
export class OverflowMenuComponent implements OnChanges, OnDestroy {
  @Input() open = false;
  @Input() triggerElement: HTMLElement | null = null;
  @Output() closed = new EventEmitter<void>();
  @ViewChild('menu') private readonly menuRef?: ElementRef<HTMLElement>;

  readonly auth = inject(AuthService);
  private readonly router = inject(Router);
  readonly appVersion = APP_VERSION;

  private previouslyFocused: HTMLElement | null = null;
  private readonly onKeyDown = (event: KeyboardEvent) => this.handleKeyDown(event);

  ngOnChanges(): void {
    if (this.open) {
      this.onOpen();
    } else {
      this.onCloseCleanup();
    }
  }

  ngOnDestroy(): void {
    document.removeEventListener('keydown', this.onKeyDown);
  }

  onBackdropMouseDown(event: MouseEvent): void {
    if (!this.menuRef?.nativeElement.contains(event.target as Node)) {
      this.closed.emit();
    }
  }

  handleLogout(): void {
    this.auth.logout();
    this.router.navigate(['/login']);
    this.closed.emit();
  }

  handleSettingsClick(): void {
    this.router.navigate(['/settings'], { state: { from: this.router.url } });
    this.closed.emit();
  }

  private onOpen(): void {
    this.previouslyFocused = document.activeElement as HTMLElement | null;
    document.addEventListener('keydown', this.onKeyDown);
    queueMicrotask(() => {
      this.menuRef?.nativeElement.querySelector<HTMLElement>(FOCUSABLE_SELECTOR)?.focus();
    });
  }

  private onCloseCleanup(): void {
    document.removeEventListener('keydown', this.onKeyDown);
    (this.triggerElement ?? this.previouslyFocused)?.focus();
  }

  private handleKeyDown(event: KeyboardEvent): void {
    if (event.key === 'Escape') {
      event.preventDefault();
      this.closed.emit();
      return;
    }

    if (event.key !== 'Tab' || !this.menuRef) return;

    const focusable = Array.from(
      this.menuRef.nativeElement.querySelectorAll<HTMLElement>(FOCUSABLE_SELECTOR),
    );
    if (focusable.length === 0) return;

    const first = focusable[0];
    const last = focusable[focusable.length - 1];

    if (event.shiftKey && document.activeElement === first) {
      event.preventDefault();
      last.focus();
    } else if (!event.shiftKey && document.activeElement === last) {
      event.preventDefault();
      first.focus();
    }
  }
}

// react/src/components/OverflowMenu.tsx
// react/src/components/OverflowMenu.tsx
import { useTranslation } from "react-i18next";
import { useLocation, useNavigate } from "react-router-dom";
import { useEffect, useRef, type RefObject } from "react";
import { createPortal } from "react-dom";
import { logout } from "../auth";
import { useAuth } from "../hooks/useAuth";
import { ThemeToggle } from "./ThemeToggle";
import { LanguageToggle } from "./LanguageToggle";

const APP_VERSION = import.meta.env.VITE_APP_VERSION ?? "dev";

interface OverflowMenuProps {
  open: boolean;
  onClose: () => void;
  triggerRef?: RefObject<HTMLElement | null>;
}

const FOCUSABLE_SELECTOR =
  'a[href], button:not([disabled]), input:not([disabled]), [tabindex]:not([tabindex="-1"])';

export function OverflowMenu({ open, onClose, triggerRef }: OverflowMenuProps) {
  const { t } = useTranslation();
  const navigate = useNavigate();
  const location = useLocation();
  const menuRef = useRef<HTMLElement>(null);

  const { isLoggedIn } = useAuth();

  const handleLogout = () => {
    logout();
    navigate("/login");
    onClose();
  };

  const handleSettingsClick = () => {
    navigate("/settings", { state: { from: location.pathname } });
    onClose();
  };

  const handleGithubClick = () => {
    window.open("https://github.com/coliver/chess-trainer", "_blank");
    onClose();
  };

  // Close menu on outside click
  useEffect(() => {
    function handleClickOutside(event: MouseEvent) {
      if (menuRef.current && !menuRef.current.contains(event.target as Node)) {
        onClose();
      }
    }

    if (open) {
      document.addEventListener("mousedown", handleClickOutside);
      return () => {
        document.removeEventListener("mousedown", handleClickOutside);
      };
    }
  }, [open, onClose]);

  // Focus the menu on open, return focus to the trigger on close, and trap
  // focus + handle Escape while open so keyboard/screen-reader users can't
  // tab into the page behind this modal-like overlay.
  useEffect(() => {
    if (!open) return;

    const previouslyFocused = document.activeElement as HTMLElement | null;
    const trigger = triggerRef?.current;
    const firstItem = menuRef.current?.querySelector<HTMLElement>(
      FOCUSABLE_SELECTOR,
    );
    firstItem?.focus();

    function handleKeyDown(event: KeyboardEvent) {
      if (event.key === "Escape") {
        event.preventDefault();
        onClose();
        return;
      }

      if (event.key !== "Tab" || !menuRef.current) return;

      const focusable = Array.from(
        menuRef.current.querySelectorAll<HTMLElement>(FOCUSABLE_SELECTOR),
      );
      if (focusable.length === 0) return;

      const first = focusable[0];
      const last = focusable[focusable.length - 1];

      if (event.shiftKey && document.activeElement === first) {
        event.preventDefault();
        last.focus();
      } else if (!event.shiftKey && document.activeElement === last) {
        event.preventDefault();
        first.focus();
      }
    }

    document.addEventListener("keydown", handleKeyDown);
    return () => {
      document.removeEventListener("keydown", handleKeyDown);
      (trigger ?? previouslyFocused)?.focus();
    };
  }, [open, onClose, triggerRef]);

  if (!open) return null;

  return createPortal(
    <div className="overflow-menu" data-testid="overflow-menu-backdrop">
      <nav
        className="overflow-menu-items"
        ref={menuRef}
        role="dialog"
        aria-modal="true"
        aria-label={t("header.nav")}
      >
        {isLoggedIn && (
          <>
            <button
              className="overflow-menu-item"
              onClick={handleSettingsClick}
            >
              {t("header.settings")}
            </button>
            <button
              className="overflow-menu-item"
              onClick={handleLogout}
            >
              {t("header.logout")}
            </button>
          </>
        )}
        <a
          className="overflow-menu-item"
          href="https://github.com/coliver/chess-trainer"
          target="_blank"
          rel="noopener noreferrer"
          onClick={handleGithubClick}
        >
          {t("header.viewSource")}
        </a>
        <div className="overflow-menu-divider" />
        <div className="overflow-menu-control">
          <span className="overflow-menu-label">Language</span>
          <LanguageToggle />
        </div>
        <div className="overflow-menu-control">
          <span className="overflow-menu-label">{t("theme.toggle")}</span>
          <ThemeToggle />
        </div>
        <div className="overflow-menu-divider" />
        <div className="overflow-menu-footer">
          <span className="overflow-menu-version">{APP_VERSION}</span>
        </div>
      </nav>
    </div>,
    document.body,
  );
}
