// frontend/angular/src/app/shared/settings-radio-group.component.ts
import { Component, ChangeDetectionStrategy, EventEmitter, Input, Output } from '@angular/core';
import { NgTemplateOutlet } from '@angular/common';

export interface SettingsRadioOption {
  value: string;
  label: string;
}

/** Angular counterpart of react/src/components/SettingsRadioGroup.tsx. */
@Component({
  selector: 'app-settings-radio-group',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.Eager,
  imports: [NgTemplateOutlet],
  template: `
    @if (rowLabel) {
      <div class="settings-row">
        <span class="settings-row-label">{{ rowLabel }}</span>
        <ng-container [ngTemplateOutlet]="group" />
      </div>
    } @else {
      <ng-container [ngTemplateOutlet]="group" />
    }

    <ng-template #group>
      <div
        class="settings-radio-group"
        [class.settings-radio-group--stacked]="stacked"
        role="radiogroup"
        [attr.aria-label]="ariaLabel"
      >
        @for (option of options; track option.value) {
          <label class="settings-radio">
            <input
              type="radio"
              [name]="name"
              [value]="option.value"
              [checked]="value === option.value"
              (change)="valueChange.emit(option.value)"
            />
            {{ option.label }}
          </label>
        }
      </div>
    </ng-template>
  `,
})
export class SettingsRadioGroupComponent {
  @Input({ required: true }) name = '';
  @Input({ required: true }) ariaLabel = '';
  @Input() rowLabel?: string;
  @Input() stacked = false;
  @Input({ required: true }) value = '';
  @Input({ required: true }) options: SettingsRadioOption[] = [];
  @Output() valueChange = new EventEmitter<string>();
}

// react/src/components/SettingsRadioGroup.tsx
type Option<T extends string> = {
  value: T;
  label: string;
};

type Props<T extends string> = {
  name: string;
  ariaLabel: string;
  rowLabel?: string;
  stacked?: boolean;
  value: T;
  options: Option<T>[];
  onChange: (value: T) => void;
};

export function SettingsRadioGroup<T extends string>({
  name,
  ariaLabel,
  rowLabel,
  stacked,
  value,
  options,
  onChange,
}: Props<T>) {
  const group = (
    <div
      className={`settings-radio-group${stacked ? " settings-radio-group--stacked" : ""}`}
      role="radiogroup"
      aria-label={ariaLabel}
    >
      {options.map((option) => (
        <label key={option.value} className="settings-radio">
          <input
            type="radio"
            name={name}
            value={option.value}
            checked={value === option.value}
            onChange={() => onChange(option.value)}
          />
          {option.label}
        </label>
      ))}
    </div>
  );

  if (!rowLabel) return group;

  return (
    <div className="settings-row">
      <span className="settings-row-label">{rowLabel}</span>
      {group}
    </div>
  );
}
