// angular/src/app/pages/register/register.component.ts
import { Component, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { AuthService } from '../../core/auth.service';

@Component({
  selector: 'app-register',
  imports: [FormsModule],
  template: `
    <main class="page">
      <div class="card">
        <h1 class="title">Register</h1>
        <p class="subtitle">Create your account.</p>

        @if (success) {
          <p>Registered—now log in.</p>
        } @else {
          <form class="auth-form" (ngSubmit)="submit()">
            <label class="auth-field">
              <span class="auth-label">Email</span>
              <input
                class="text-input"
                name="email"
                type="email"
                [(ngModel)]="email"
                required
                autocomplete="email"
              />
            </label>

            <label class="auth-field">
              <span class="auth-label">Username</span>
              <input
                class="text-input"
                name="username"
                [(ngModel)]="username"
                required
                autocomplete="username"
              />
            </label>

            <label class="auth-field">
              <span class="auth-label">Password</span>
              <input
                class="text-input"
                name="password"
                type="password"
                [(ngModel)]="password"
                required
                autocomplete="new-password"
              />
            </label>

            <button class="btn" type="submit" [disabled]="submitting">
              {{ submitting ? 'Registering…' : 'Register' }}
            </button>

            @if (error) {
              <div class="auth-error">{{ error }}</div>
            }
          </form>
        }
      </div>
    </main>
  `,
})
export class RegisterComponent {
  private readonly auth = inject(AuthService);
  private readonly router = inject(Router);

  email = '';
  username = '';
  password = '';
  error: string | null = null;
  success = false;
  submitting = false;

  submit(): void {
    this.error = null;
    this.submitting = true;
    this.auth.register(this.email, this.username, this.password).subscribe({
      next: () => {
        this.success = true;
        this.router.navigate(['/login']);
      },
      error: (err) => {
        this.error = err?.error?.detail ?? 'Failed to register. Please try again later.';
        this.submitting = false;
      },
    });
  }
}

// frontend/src/Register.tsx
import { useState } from "react";

export default function Register() {
  const [email, setEmail] = useState("");
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState(false);
  const [submitting, setSubmitting] = useState(false);

const handleSubmit = async (e: React.SyntheticEvent<HTMLFormElement>) => {    
    e.preventDefault();
    setError(null);
    setSubmitting(true);

    try {
      const resp = await fetch("/api/auth/register", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ email, username, password }),
      });

      if (!resp.ok) {
        setError(await resp.text());
        return;
      }

      setSuccess(true);
    } catch (err) {
      setError("Failed to register. Please try again later.");
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div
      style={{ maxWidth: 420, margin: "40px auto", fontFamily: "sans-serif" }}
    >
      <h1>Register</h1>

      {success ? (
        <p>Registered—now log in.</p>
      ) : (
        <form onSubmit={handleSubmit}>
          <label>
            Email
            <input
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              type="email"
              required
            />
          </label>

          <label style={{ display: "block", marginTop: 12 }}>
            Username
            <input
              value={username}
              onChange={(e) => setUsername(e.target.value)}
              required
            />
          </label>

          <label style={{ display: "block", marginTop: 12 }}>
            Password
            <input
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              type="password"
              required
            />
          </label>

          <button disabled={submitting} type="submit" style={{ marginTop: 16 }}>
            {submitting ? "Registering..." : "Register"}
          </button>

          {error && (
            <div
              style={{
                marginTop: 12,
                color: "crimson",
                whiteSpace: "pre-wrap",
              }}
            >
              {error}
            </div>
          )}
        </form>
      )}
    </div>
  );
}
